// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

/**
 * All primitive types
 */
export const PrimitivesSchema = z.object({
  booleanVal: z.boolean(),
  integerVal: z.int(),
  numberVal: z.number(),
  stringVal: z.string(),
}).meta({ description: "All primitive types" });

export type Primitives = z.infer<typeof PrimitivesSchema>;

/**
 * String formats for validation
 */
export const FormatsSchema = z.object({
  date: z.iso.date().optional().meta({ description: "Date only (YYYY-MM-DD)" }),
  dateTime: z.iso.datetime().optional().meta({ description: "Full timestamp with timezone" }),
  email: z.email().optional().meta({ description: "User email address" }),
  ipv4: z.ipv4().optional().meta({ description: "IPv4 address" }),
  ipv6: z.ipv6().optional().meta({ description: "IPv6 address" }),
  time: z.iso.time().optional().meta({ description: "Time only (HH:MM:SS)" }),
  uri: z.url().optional().meta({ description: "Resource URL" }),
  uuid: z.uuid().optional().meta({ description: "Unique identifier" }),
}).meta({ description: "String formats for validation" });

export type Formats = z.infer<typeof FormatsSchema>;

export const ArraysSchema = z.object({
  minMaxArray: z.array(z.string()).min(1).max(10).optional().meta({ description: "Array with size constraints" }),
});

export type Arrays = z.infer<typeof ArraysSchema>;

export const NumbersSchema = z.object({
  exclusiveRange: z.number().gt(0).lt(100).optional().meta({ description: "Number with exclusive bounds" }),
  minMaxInteger: z.int().gte(1).lte(999).optional().meta({ description: "Integer with constraints" }),
  minMaxNumber: z.number().gte(0).lte(100).optional().meta({ description: "Number with inclusive bounds" }),
});

export type Numbers = z.infer<typeof NumbersSchema>;

export const StringsSchema = z.object({
  minMaxString: z.string().min(5).max(50).optional().meta({ description: "String with length constraints" }),
  patternString: z.string().regex(/^[A-Z][a-z]+$/).optional().meta({ description: "String matching regex pattern" }),
});

export type Strings = z.infer<typeof StringsSchema>;

/**
 * Validation constraints
 */
export const ConstraintsSchema = z.object({
  arrays: ArraysSchema.optional(),
  numbers: NumbersSchema.optional(),
  strings: StringsSchema.optional(),
}).meta({ description: "Validation constraints" });

export type Constraints = z.infer<typeof ConstraintsSchema>;

/**
 * Mixed type enumeration
 */
export const MixedEnumSchema = z.union([z.literal("string"), z.literal(42), z.literal(true), z.literal(null)]).meta({ description: "Mixed type enumeration" });

export type MixedEnum = z.infer<typeof MixedEnumSchema>;

/**
 * Number enumeration
 */
export const NumberEnumSchema = z.union([z.literal(1), z.literal(2), z.literal(3)]).meta({ description: "Number enumeration" });

export type NumberEnum = z.infer<typeof NumberEnumSchema>;

/**
 * String enumeration
 */
export const StringEnumSchema = z.enum(["option1", "option2", "option3"]).meta({ description: "String enumeration" });

export type StringEnum = z.infer<typeof StringEnumSchema>;

/**
 * Enumeration types
 */
export const EnumsSchema = z.object({
  mixedEnum: MixedEnumSchema.optional().meta({ description: "Mixed type enumeration" }),
  numberEnum: NumberEnumSchema.optional().meta({ description: "Number enumeration" }),
  stringEnum: StringEnumSchema.optional().meta({ description: "String enumeration" }),
}).meta({ description: "Enumeration types" });

export type Enums = z.infer<typeof EnumsSchema>;

export const ObjectArrayItemSchema = z.object({
  id: z.string().optional(),
  value: z.number().optional(),
});

export type ObjectArrayItem = z.infer<typeof ObjectArrayItemSchema>;

/**
 * Array types
 */
export const Arrays2Schema = z.object({
  numberArray: z.array(z.number()).optional().meta({ description: "Array of numbers" }),
  objectArray: z.array(ObjectArrayItemSchema).optional().meta({ description: "Array of objects" }),
  stringArray: z.array(z.string()).optional().meta({ description: "Array of strings" }),
}).meta({ description: "Array types" });

export type Arrays2 = z.infer<typeof Arrays2Schema>;

export const Level2Schema = z.object({
  level3: z.string().optional().meta({ description: "Three levels deep" }),
});

export type Level2 = z.infer<typeof Level2Schema>;

export const Level1Schema = z.object({
  level2: Level2Schema.optional(),
});

export type Level1 = z.infer<typeof Level1Schema>;

/**
 * Nested object structure
 */
export const NestedSchema = z.object({
  level1: Level1Schema.optional(),
}).meta({ description: "Nested object structure" });

export type Nested = z.infer<typeof NestedSchema>;

export const OptionalObjectSchema = z.object({
  field: z.string().optional(),
});

export type OptionalObject = z.infer<typeof OptionalObjectSchema>;

/**
 * Required vs optional fields
 */
export const NullableSchema = z.object({
  optionalArray: z.array(z.string()).optional(),
  optionalNumber: z.number().optional(),
  optionalObject: OptionalObjectSchema.optional(),
  optionalString: z.string().optional().meta({ description: "This field is optional" }),
  requiredString: z.string().meta({ description: "This field is required" }),
}).meta({ description: "Required vs optional fields" });

export type Nullable = z.infer<typeof NullableSchema>;

/**
 * Any additional properties allowed
 */
export const FlexibleSchema = z.looseObject({
  enabled: z.boolean().optional(),
  version: z.string(),
}).meta({ description: "Any additional properties allowed" });

export type Flexible = z.infer<typeof FlexibleSchema>;

/**
 * No additional properties allowed
 */
export const StrictSchema = z.strictObject({
  id: z.string(),
  name: z.string().optional(),
}).meta({ description: "No additional properties allowed" });

export type Strict = z.infer<typeof StrictSchema>;

/**
 * Additional properties must be numbers
 */
export const TypedMapSchema = z.object({
  source: z.string().optional(),
  timestamp: z.string(),
}).catchall(z.number()).meta({ description: "Additional properties must be numbers" });

export type TypedMap = z.infer<typeof TypedMapSchema>;

/**
 * Additional properties patterns
 */
export const AdditionalPropsSchema = z.object({
  flexible: FlexibleSchema.optional().meta({ description: "Any additional properties allowed" }),
  strict: StrictSchema.optional().meta({ description: "No additional properties allowed" }),
  typedMap: TypedMapSchema.optional().meta({ description: "Additional properties must be numbers" }),
}).meta({ description: "Additional properties patterns" });

export type AdditionalProps = z.infer<typeof AdditionalPropsSchema>;

/**
 * Reserved keywords in TypeScript and Python
 */
export const ReservedKeywordsSchema = z.object({
  as: z.string().optional(),
  async: z.string().optional(),
  "await": z.string().optional(),
  "class": z.string().optional(),
  def: z.string().optional(),
  "export": z.string().optional(),
  from: z.string().optional(),
  "import": z.string().optional(),
  "interface": z.string().optional(),
  lambda: z.string().optional(),
  "return": z.string().optional(),
  type: z.string().optional(),
  "yield": z.string().optional(),
}).meta({ description: "Reserved keywords in TypeScript and Python" });

export type ReservedKeywords = z.infer<typeof ReservedKeywordsSchema>;

/**
 * Special characters in property names
 */
export const SpecialCharsSchema = z.object({
  $dollar: z.string().optional(),
  "123numeric": z.string().optional(),
  "@special": z.string().optional(),
  PascalCase: z.string().optional(),
  camelCase: z.string().optional(),
  "kebab-case": z.string().optional(),
  snake_case: z.string().optional(),
  "with spaces": z.string().optional(),
  "with.dots": z.string().optional(),
}).meta({ description: "Special characters in property names" });

export type SpecialChars = z.infer<typeof SpecialCharsSchema>;

/**
 * Edge cases: reserved keywords and special characters
 */
export const EdgeCasesSchema = z.object({
  emptyConfig: z.record(z.string(), z.unknown()).optional().meta({ description: "Empty object with no properties" }),
  reservedKeywords: ReservedKeywordsSchema.optional().meta({ description: "Reserved keywords in TypeScript and Python" }),
  specialChars: SpecialCharsSchema.optional().meta({ description: "Special characters in property names" }),
}).meta({ description: "Edge cases: reserved keywords and special characters" });

export type EdgeCases = z.infer<typeof EdgeCasesSchema>;

/**
 * Comprehensive test of all basic types, formats, constraints, and edge cases
 */
export const FoundationSchema = z.object({
  primitives: PrimitivesSchema.meta({ description: "All primitive types" }),
  formats: FormatsSchema.optional().meta({ description: "String formats for validation" }),
  constraints: ConstraintsSchema.optional().meta({ description: "Validation constraints" }),
  enums: EnumsSchema.optional().meta({ description: "Enumeration types" }),
  arrays: Arrays2Schema.optional().meta({ description: "Array types" }),
  nested: NestedSchema.optional().meta({ description: "Nested object structure" }),
  nullable: NullableSchema.optional().meta({ description: "Required vs optional fields" }),
  additionalProps: AdditionalPropsSchema.optional().meta({ description: "Additional properties patterns" }),
  edgeCases: EdgeCasesSchema.optional().meta({ description: "Edge cases: reserved keywords and special characters" }),
}).meta({ description: "Comprehensive test of all basic types, formats, constraints, and edge cases" });

export type Foundation = z.infer<typeof FoundationSchema>;
