// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

export type Type = "email";

export const TypeSchema = z.enum(["email"]);

/**
 * Email channel configuration
 */
export interface Channel {
  subject: string;
  /**
   * @format email
   */
  to: string;
  type: Type;
}

export const ChannelSchema = z.object({
  subject: z.string(),
  to: z.email(),
  type: TypeSchema,
}).meta({ description: "Email channel configuration" });

export type Type2 = "sms";

export const Type2Schema = z.enum(["sms"]);

/**
 * SMS channel configuration
 */
export interface Channel1 {
  countryCode?: string;
  phoneNumber: string;
  type: Type2;
}

export const Channel1Schema = z.object({
  countryCode: z.string().optional(),
  phoneNumber: z.string(),
  type: Type2Schema,
}).meta({ description: "SMS channel configuration" });

export type Type3 = "push";

export const Type3Schema = z.enum(["push"]);

/**
 * Push notification configuration
 */
export interface Channel2 {
  badge?: number;
  deviceId: string;
  type: Type3;
}

export const Channel2Schema = z.object({
  badge: z.number().optional(),
  deviceId: z.string(),
  type: Type3Schema,
}).meta({ description: "Push notification configuration" });

export type Format = "text";

export const FormatSchema = z.enum(["text"]);

/**
 * Plain text content
 */
export interface Content {
  body: string;
  format: Format;
}

export const ContentSchema = z.object({
  body: z.string(),
  format: FormatSchema,
}).meta({ description: "Plain text content" });

export type Format2 = "html";

export const Format2Schema = z.enum(["html"]);

/**
 * HTML content
 */
export interface Content1 {
  body: string;
  css?: string;
  format: Format2;
}

export const Content1Schema = z.object({
  body: z.string(),
  css: z.string().optional(),
  format: Format2Schema,
}).meta({ description: "HTML content" });

/**
 * Notification priority level
 */
export type Priority = "low" | "normal" | "high" | "urgent";

export const PrioritySchema = z.enum(["low", "normal", "high", "urgent"]).meta({ description: "Notification priority level" });

/**
 * A notification that can be sent via multiple channels
 */
export interface Notification {
  /** Unique notification ID */
  id: string;
  /**
   * When the notification was created
   * @format date-time
   */
  timestamp: string;
  /** Delivery channel configuration (email, SMS, or push) */
  channel: Channel | Channel1 | Channel2;
  /** Notification content (text or HTML) */
  content: Content | Content1;
  /** Notification priority level */
  priority?: Priority;
}

export const NotificationSchema = z.object({
  id: z.string().meta({ description: "Unique notification ID" }),
  timestamp: z.iso.datetime().meta({ description: "When the notification was created" }),
  channel: z.union([ChannelSchema, Channel1Schema, Channel2Schema]).meta({ description: "Delivery channel configuration (email, SMS, or push)" }),
  content: z.union([ContentSchema, Content1Schema]).meta({ description: "Notification content (text or HTML)" }),
  priority: PrioritySchema.optional().meta({ description: "Notification priority level" }),
}).meta({ description: "A notification that can be sent via multiple channels" });
