// Code generated by schemagen. DO NOT EDIT.

import type { Settings } from './settings';

/**
 * Application configuration (YAML format test)
 */
export interface Config {
  appName: string;
  settings?: Settings;
  version: string;
}
