// Code generated by schemagen. DO NOT EDIT.

/**
 * Application settings
 */
export interface Settings {
  debug?: boolean;
  logLevel?: "debug" | "info" | "warn" | "error";
  maxConnections?: number;
}
