// Code generated by schemagen. DO NOT EDIT.

package models

import (
	_ "github.com/go-playground/validator/v10"
	"github.com/google/uuid"
)

type Code string

const (
	CodeUS Code = "US"
	CodeCA Code = "CA"
	CodeUK Code = "UK"
	CodeFR Code = "FR"
	CodeDE Code = "DE"
	CodeJP Code = "JP"
)

// Country Country information
type Country struct {
	Name string `json:"name" validate:"required"`
	Code Code `json:"code" validate:"required"`
}

// Address Address with country reference
type Address struct {
	Street string `json:"street" validate:"required"`
	City string `json:"city" validate:"required"`
	ZipCode *string `json:"zipCode,omitempty"`
	// Reference to Country
	Country Country `json:"country" validate:"required"`
}

// Office Office with address reference
type Office struct {
	Name string `json:"name" validate:"required"`
	// Reference to Address (which references Country)
	Address Address `json:"address" validate:"required"`
	Employees *int `json:"employees,omitempty" validate:"gte=1"`
}

// Organization Organization schema with chained internal references
type Organization struct {
	Id uuid.UUID `json:"id" validate:"required,uuid"`
	Name string `json:"name" validate:"required"`
	// Main office (references Office → Address → Country)
	Headquarters Office `json:"headquarters" validate:"required"`
	// Branch offices (reuses Office type multiple times)
	Branches *[]Office `json:"branches,omitempty"`
}