// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

export type Code = "US" | "CA" | "UK" | "FR" | "DE" | "JP";

export const CodeSchema = z.enum(["US", "CA", "UK", "FR", "DE", "JP"]);

/**
 * Country information
 */
export interface Country {
  name: string;
  code: Code;
}

export const CountrySchema = z.object({
  name: z.string(),
  code: CodeSchema,
}).meta({ description: "Country information" });

/**
 * Address with country reference
 */
export interface Address {
  street: string;
  city: string;
  zipCode?: string;
  /** Reference to Country */
  country: Country;
}

export const AddressSchema = z.object({
  street: z.string(),
  city: z.string(),
  zipCode: z.string().optional(),
  country: CountrySchema.meta({ description: "Reference to Country" }),
}).meta({ description: "Address with country reference" });

/**
 * Office with address reference
 */
export interface Office {
  name: string;
  /** Reference to Address (which references Country) */
  address: Address;
  employees?: number;
}

export const OfficeSchema = z.object({
  name: z.string(),
  address: AddressSchema.meta({ description: "Reference to Address (which references Country)" }),
  employees: z.int().gte(1).optional(),
}).meta({ description: "Office with address reference" });

/**
 * Organization schema with chained internal references
 */
export interface Organization {
  /**
   * @format uuid
   */
  id: string;
  name: string;
  /** Main office (references Office → Address → Country) */
  headquarters: Office;
  /** Branch offices (reuses Office type multiple times) */
  branches?: Office[];
}

export const OrganizationSchema = z.object({
  id: z.uuid(),
  name: z.string(),
  headquarters: OfficeSchema.meta({ description: "Main office (references Office → Address → Country)" }),
  branches: z.array(OfficeSchema).optional().meta({ description: "Branch offices (reuses Office type multiple times)" }),
}).meta({ description: "Organization schema with chained internal references" });
