// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

/**
 * Type with cyclic reference to itself
 */
export interface CyclicRef {
  /** Unique identifier */
  id: string;
  name?: string;
  /** Reference to parent node (cyclic) */
  parent?: CyclicRef;
  /** Child nodes (cyclic) */
  children?: CyclicRef[];
}

export const CyclicRefSchema = z.object({
  id: z.string().meta({ description: "Unique identifier" }),
  name: z.string().optional(),
  get parent() { return CyclicRefSchema.optional().meta({ description: "Reference to parent node (cyclic)" }) },
  get children() { return z.array(CyclicRefSchema).optional().meta({ description: "Child nodes (cyclic)" }) },
}).meta({ description: "Type with cyclic reference to itself" });
