// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

/**
 * This has "double quotes" and '''triple single''' and """triple double""" quotes
 */
export interface DescriptionQuotes {
  /** Field with "quotes" and \backslash in description */
  field?: string;
}

export const DescriptionQuotesSchema = z.object({
  field: z.string().optional().meta({ description: "Field with \"quotes\" and \\backslash in description" }),
}).meta({ description: "This has \"double quotes\" and '''triple single''' and \"\"\"triple double\"\"\" quotes" });
