// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

/**
 * Message priority level
 */
export type Priority = "low" | "normal" | "high" | "critical";

export const PrioritySchema = z.enum(["low", "normal", "high", "critical"]).meta({ description: "Message priority level" });

/**
 * Message in a queue or topic
 */
export interface Message {
  /**
   * Unique message identifier
   * @format uuid
   */
  id: string;
  /** Message topic or queue name */
  topic: string;
  /** Message payload (any structure) */
  payload: Record<string, any>;
  /**
   * When the message was created
   * @format date-time
   */
  timestamp: string;
  /** Time to live in seconds */
  ttl?: number;
  /** Number of delivery attempts */
  retryCount?: number;
  /** Message priority level */
  priority?: Priority;
}

export const MessageSchema = z.object({
  id: z.uuid().meta({ description: "Unique message identifier" }),
  topic: z.string().meta({ description: "Message topic or queue name" }),
  payload: z.record(z.string(), z.unknown()).meta({ description: "Message payload (any structure)" }),
  timestamp: z.iso.datetime().meta({ description: "When the message was created" }),
  ttl: z.int().gte(0).optional().meta({ description: "Time to live in seconds" }),
  retryCount: z.int().gte(0).lte(10).optional().meta({ description: "Number of delivery attempts" }),
  priority: PrioritySchema.optional().meta({ description: "Message priority level" }),
}).meta({ description: "Message in a queue or topic" });

/**
 * Delivery guarantee level
 */
export type DeliveryMode = "at-most-once" | "at-least-once" | "exactly-once";

export const DeliveryModeSchema = z.enum(["at-most-once", "at-least-once", "exactly-once"]).meta({ description: "Delivery guarantee level" });

/**
 * Subscription to a topic
 */
export interface Subscription {
  /**
   * @format uuid
   */
  id: string;
  /** Topic pattern to subscribe to */
  topic: string;
  /** Message filtering rules */
  filters?: Record<string, string>;
  /** Delivery guarantee level */
  deliveryMode: DeliveryMode;
  /**
   * Webhook URL for message delivery
   * @format uri
   */
  endpoint?: string;
}

export const SubscriptionSchema = z.object({
  id: z.uuid(),
  topic: z.string().meta({ description: "Topic pattern to subscribe to" }),
  filters: z.record(z.string(), z.string()).optional().meta({ description: "Message filtering rules" }),
  deliveryMode: DeliveryModeSchema.meta({ description: "Delivery guarantee level" }),
  endpoint: z.url().optional().meta({ description: "Webhook URL for message delivery" }),
}).meta({ description: "Subscription to a topic" });

/**
 * API error details
 */
export interface Error {
  /** Error code */
  code: string;
  /** Human-readable error message */
  message: string;
  /** Field that caused the error */
  field?: string;
  /** Additional error context */
  details?: Record<string, any>;
}

export const ErrorSchema = z.object({
  code: z.string().meta({ description: "Error code" }),
  message: z.string().meta({ description: "Human-readable error message" }),
  field: z.string().optional().meta({ description: "Field that caused the error" }),
  details: z.record(z.string(), z.unknown()).optional().meta({ description: "Additional error context" }),
}).meta({ description: "API error details" });

/**
 * Pagination information
 */
export interface Pagination {
  /** Current page number */
  page: number;
  /** Items per page */
  pageSize: number;
  /** Total number of pages */
  totalPages: number;
  /** Total number of items */
  totalItems: number;
  /** Whether there is a next page */
  hasNext?: boolean;
  /** Whether there is a previous page */
  hasPrevious?: boolean;
}

export const PaginationSchema = z.object({
  page: z.int().gte(1).meta({ description: "Current page number" }),
  pageSize: z.int().gte(1).lte(100).meta({ description: "Items per page" }),
  totalPages: z.int().gte(0).meta({ description: "Total number of pages" }),
  totalItems: z.int().gte(0).meta({ description: "Total number of items" }),
  hasNext: z.boolean().optional().meta({ description: "Whether there is a next page" }),
  hasPrevious: z.boolean().optional().meta({ description: "Whether there is a previous page" }),
}).meta({ description: "Pagination information" });

/**
 * Response metadata (inline object, not a $def)
 */
export interface Metadata {
  /** Server region that handled the request */
  region?: string;
  /**
   * Unique request identifier for tracing
   * @format uuid
   */
  requestId: string;
  /**
   * When the response was generated
   * @format date-time
   */
  timestamp: string;
  /** API version */
  version: string;
}

export const MetadataSchema = z.object({
  region: z.string().optional().meta({ description: "Server region that handled the request" }),
  requestId: z.uuid().meta({ description: "Unique request identifier for tracing" }),
  timestamp: z.iso.datetime().meta({ description: "When the response was generated" }),
  version: z.string().meta({ description: "API version" }),
}).meta({ description: "Response metadata (inline object, not a $def)" });

/**
 * Nested inline object
 */
export interface Throughput {
  bytesPerSecond?: number;
  messagesPerSecond?: number;
}

export const ThroughputSchema = z.object({
  bytesPerSecond: z.number().gte(0).optional(),
  messagesPerSecond: z.number().gte(0).optional(),
}).meta({ description: "Nested inline object" });

/**
 * Queue statistics (inline object)
 */
export interface Stats {
  activeSubscriptions?: number;
  pendingMessages?: number;
  /** Nested inline object */
  throughput?: Throughput;
  totalMessages?: number;
}

export const StatsSchema = z.object({
  activeSubscriptions: z.int().gte(0).optional(),
  pendingMessages: z.int().gte(0).optional(),
  throughput: ThroughputSchema.optional().meta({ description: "Nested inline object" }),
  totalMessages: z.int().gte(0).optional(),
}).meta({ description: "Queue statistics (inline object)" });

/**
 * Real-world messaging API with pagination, errors, and message queue concepts
 */
export interface MessagingAPI {
  /** List of messages */
  messages?: Message[];
  /** Active subscriptions */
  subscriptions?: Subscription[];
  pagination?: Pagination;
  /** Any errors encountered */
  errors?: Error[];
  /** Response metadata (inline object, not a $def) */
  metadata: Metadata;
  /** Queue statistics (inline object) */
  stats?: Stats;
}

export const MessagingAPISchema = z.object({
  messages: z.array(MessageSchema).optional().meta({ description: "List of messages" }),
  subscriptions: z.array(SubscriptionSchema).optional().meta({ description: "Active subscriptions" }),
  pagination: PaginationSchema.optional(),
  errors: z.array(ErrorSchema).optional().meta({ description: "Any errors encountered" }),
  metadata: MetadataSchema.meta({ description: "Response metadata (inline object, not a $def)" }),
  stats: StatsSchema.optional().meta({ description: "Queue statistics (inline object)" }),
}).meta({ description: "Real-world messaging API with pagination, errors, and message queue concepts" });
