// Code generated by schemagen. DO NOT EDIT.

package models

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/uuid"
	"time"
)

// DeliveryMode Delivery guarantee level
type DeliveryMode string

const (
	DeliveryModeAT_MOST_ONCE DeliveryMode = "at-most-once"
	DeliveryModeAT_LEAST_ONCE DeliveryMode = "at-least-once"
	DeliveryModeEXACTLY_ONCE DeliveryMode = "exactly-once"
)

// Error API error details
type Error struct {
	// Error code
	Code string `json:"code" validate:"required"`
	// Human-readable error message
	Message string `json:"message" validate:"required"`
	// Field that caused the error
	Field *string `json:"field,omitempty"`
	// Additional error context
	Details *map[string]interface{} `json:"details,omitempty"`
}

// Message Message in a queue or topic
type Message struct {
	// Unique message identifier
	Id uuid.UUID `json:"id" validate:"required,uuid"`
	// Message topic or queue name
	Topic string `json:"topic" validate:"required"`
	// Message payload (any structure)
	Payload map[string]interface{} `json:"payload" validate:"required"`
	// When the message was created
	Timestamp time.Time `json:"timestamp" validate:"required"`
	// Time to live in seconds
	Ttl *int `json:"ttl,omitempty" validate:"gte=0"`
	// Number of delivery attempts
	RetryCount *int `json:"retryCount,omitempty" validate:"gte=0,lte=10"`
	// Message priority level
	Priority *Priority `json:"priority,omitempty"`
}

// MessagingAPI Real-world messaging API with pagination, errors, and message queue concepts
type MessagingAPI struct {
	// List of messages
	Messages *[]Message `json:"messages,omitempty"`
	// Active subscriptions
	Subscriptions *[]Subscription `json:"subscriptions,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
	// Any errors encountered
	Errors *[]Error `json:"errors,omitempty"`
	// Response metadata (inline object, not a $def)
	Metadata Metadata `json:"metadata" validate:"required"`
	// Queue statistics (inline object)
	Stats *Stats `json:"stats,omitempty"`
}

// Metadata Response metadata (inline object, not a $def)
type Metadata struct {
	// Server region that handled the request
	Region *string `json:"region,omitempty"`
	// Unique request identifier for tracing
	RequestId uuid.UUID `json:"requestId" validate:"required,uuid"`
	// When the response was generated
	Timestamp time.Time `json:"timestamp" validate:"required"`
	// API version
	Version string `json:"version" validate:"required"`
}

// Pagination Pagination information
type Pagination struct {
	// Current page number
	Page int `json:"page" validate:"required,gte=1"`
	// Items per page
	PageSize int `json:"pageSize" validate:"required,gte=1,lte=100"`
	// Total number of pages
	TotalPages int `json:"totalPages" validate:"required,gte=0"`
	// Total number of items
	TotalItems int `json:"totalItems" validate:"required,gte=0"`
	// Whether there is a next page
	HasNext *bool `json:"hasNext,omitempty"`
	// Whether there is a previous page
	HasPrevious *bool `json:"hasPrevious,omitempty"`
}

// Priority Message priority level
type Priority string

const (
	PriorityLOW Priority = "low"
	PriorityNORMAL Priority = "normal"
	PriorityHIGH Priority = "high"
	PriorityCRITICAL Priority = "critical"
)

// Stats Queue statistics (inline object)
type Stats struct {
	ActiveSubscriptions *int `json:"activeSubscriptions,omitempty" validate:"gte=0"`
	PendingMessages *int `json:"pendingMessages,omitempty" validate:"gte=0"`
	// Nested inline object
	Throughput *Throughput `json:"throughput,omitempty"`
	TotalMessages *int `json:"totalMessages,omitempty" validate:"gte=0"`
}

// Subscription Subscription to a topic
type Subscription struct {
	Id uuid.UUID `json:"id" validate:"required,uuid"`
	// Topic pattern to subscribe to
	Topic string `json:"topic" validate:"required"`
	// Message filtering rules
	Filters *map[string]string `json:"filters,omitempty"`
	// Delivery guarantee level
	DeliveryMode DeliveryMode `json:"deliveryMode" validate:"required"`
	// Webhook URL for message delivery
	Endpoint *string `json:"endpoint,omitempty" validate:"url"`
}

// Throughput Nested inline object
type Throughput struct {
	BytesPerSecond *float64 `json:"bytesPerSecond,omitempty" validate:"gte=0"`
	MessagesPerSecond *float64 `json:"messagesPerSecond,omitempty" validate:"gte=0"`
}