# Code generated by schemagen. DO NOT EDIT.

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field


class PingPayload(BaseModel):
    """Payload for ping event"""

    timestamp: datetime = Field(..., description="Ping timestamp")
    ttl: int = Field(..., description="Time to live in milliseconds", ge=0)
    sequence: int | None = Field(None, description="Ping sequence number", ge=0)
