# Code generated by schemagen. DO NOT EDIT.

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field


class PongPayload(BaseModel):
    """Payload for pong event (minimal response)"""

    timestamp: datetime | None = Field(None, description="Pong response timestamp")
