# Code generated by schemagen. DO NOT EDIT.

from __future__ import annotations

from pydantic import BaseModel, Field


class SubscribePayload(BaseModel):
    """Payload for subscribe event"""

    topic: str = Field(..., description="Topic to subscribe to")
    filters: dict[str, str] | None = Field(None, description="Subscription filters")
    qos: int | None = Field(None, description="Quality of service level", ge=0, le=2)
