# Code generated by schemagen. DO NOT EDIT.

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, Field


class UnsubscribePayload(BaseModel):
    """Payload for unsubscribe event"""

    subscriptionId: UUID = Field(..., description="ID of subscription to cancel")
    reason: str | None = Field(None, description="Reason for unsubscribing")
