# Code generated by schemagen. DO NOT EDIT.

from __future__ import annotations

from pydantic import BaseModel, Field


class Simple(BaseModel):
    """A simple test schema"""

    name: str = Field(..., description="The name field")
    value: int | None = Field(None, description="The numeric value")
