// Code generated by schemagen. DO NOT EDIT.

/**
 * Comprehensive test of all basic types, formats, constraints, and edge cases
 */
export interface Foundation {
  /** All primitive types */
  primitives: {
    booleanVal: boolean;
    integerVal: number;
    numberVal: number;
    stringVal: string;
  };
  /** String formats for validation */
  formats?: {
    /**
     * Date only (YYYY-MM-DD)
     * @format date
     */
    date?: string;
    /**
     * Full timestamp with timezone
     * @format date-time
     */
    dateTime?: string;
    /**
     * User email address
     * @format email
     */
    email?: string;
    /**
     * IPv4 address
     * @format ipv4
     */
    ipv4?: string;
    /**
     * IPv6 address
     * @format ipv6
     */
    ipv6?: string;
    /**
     * Time only (HH:MM:SS)
     * @format time
     */
    time?: string;
    /**
     * Resource URL
     * @format uri
     */
    uri?: string;
    /**
     * Unique identifier
     * @format uuid
     */
    uuid?: string;
  };
  /** Validation constraints */
  constraints?: {
    arrays?: {
    /** Array with size constraints */
    minMaxArray?: string[];
  };
    numbers?: {
    /** Number with exclusive bounds */
    exclusiveRange?: number;
    /** Integer with constraints */
    minMaxInteger?: number;
    /** Number with inclusive bounds */
    minMaxNumber?: number;
  };
    strings?: {
    /** String with length constraints */
    minMaxString?: string;
    /** String matching regex pattern */
    patternString?: string;
  };
  };
  /** Enumeration types */
  enums?: {
    /** Mixed type enumeration */
    mixedEnum?: "string" | 42 | true | null;
    /** Number enumeration */
    numberEnum?: 1 | 2 | 3;
    /** String enumeration */
    stringEnum?: "option1" | "option2" | "option3";
  };
  /** Array types */
  arrays?: {
    /** Array of numbers */
    numberArray?: number[];
    /** Array of objects */
    objectArray?: {
    id?: string;
    value?: number;
  }[];
    /** Array of strings */
    stringArray?: string[];
  };
  /** Nested object structure */
  nested?: {
    level1?: {
    level2?: {
    /** Three levels deep */
    level3?: string;
  };
  };
  };
  /** Required vs optional fields */
  nullable?: {
    optionalArray?: string[];
    optionalNumber?: number;
    optionalObject?: {
    field?: string;
  };
    /** This field is optional */
    optionalString?: string;
    /** This field is required */
    requiredString: string;
  };
  /** Additional properties patterns */
  additionalProps?: {
    /** Any additional properties allowed */
    flexible?: {
    enabled?: boolean;
    version: string;
  };
    /** No additional properties allowed */
    strict?: {
    id: string;
    name?: string;
  };
    /** Additional properties must be numbers */
    typedMap?: {
    source?: string;
    timestamp: string;
  };
  };
  /** Edge cases: reserved keywords and special characters */
  edgeCases?: {
    /** Empty object with no properties */
    emptyConfig?: Record<string, any>;
    /** Reserved keywords in TypeScript and Python */
    reservedKeywords?: {
    as?: string;
    async?: string;
    await?: string;
    class?: string;
    def?: string;
    export?: string;
    from?: string;
    import?: string;
    interface?: string;
    lambda?: string;
    return?: string;
    type?: string;
    yield?: string;
  };
    /** Special characters in property names */
    specialChars?: {
    $dollar?: string;
    "123numeric"?: string;
    "@special"?: string;
    PascalCase?: string;
    camelCase?: string;
    "kebab-case"?: string;
    snake_case?: string;
    "with spaces"?: string;
    "with.dots"?: string;
  };
  };
}
