// Code generated by schemagen. DO NOT EDIT.

/**
 * Blog post with deeply nested inline types for extraction testing
 */
export interface BlogPost {
  /**
   * @format uuid
   */
  id: string;
  title: string;
  content?: string;
  status: "draft" | "published" | "archived";
  /** Inline author object (should be extracted) */
  author: {
    /**
     * @format email
     */
    email: string;
    name: string;
    role?: "admin" | "editor" | "contributor";
  };
  tags?: string[];
  /** Array of inline comment objects */
  comments?: {
    /** Nested inline commenter object (should be extracted) */
    commenter: {
    /**
     * @format email
     */
    email: string;
    name: string;
  };
    /**
     * @format uuid
     */
    id: string;
    text: string;
  }[];
}
