// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

export type Status = "draft" | "published" | "archived";

export const StatusSchema = z.enum(["draft", "published", "archived"]);

export type Role = "admin" | "editor" | "contributor";

export const RoleSchema = z.enum(["admin", "editor", "contributor"]);

/**
 * Inline author object (should be extracted)
 */
export interface Author {
  /**
   * @format email
   */
  email: string;
  name: string;
  role?: Role;
}

export const AuthorSchema = z.object({
  email: z.email(),
  name: z.string(),
  role: RoleSchema.optional(),
}).meta({ description: "Inline author object (should be extracted)" });

/**
 * Nested inline commenter object (should be extracted)
 */
export interface Commenter {
  /**
   * @format email
   */
  email: string;
  name: string;
}

export const CommenterSchema = z.object({
  email: z.email(),
  name: z.string(),
}).meta({ description: "Nested inline commenter object (should be extracted)" });

/**
 * Inline comment object (should be extracted)
 */
export interface CommentsItem {
  /** Nested inline commenter object (should be extracted) */
  commenter: Commenter;
  /**
   * @format uuid
   */
  id: string;
  text: string;
}

export const CommentsItemSchema = z.object({
  commenter: CommenterSchema.meta({ description: "Nested inline commenter object (should be extracted)" }),
  id: z.uuid(),
  text: z.string(),
}).meta({ description: "Inline comment object (should be extracted)" });

/**
 * Blog post with deeply nested inline types for extraction testing
 */
export interface BlogPost {
  /**
   * @format uuid
   */
  id: string;
  title: string;
  content?: string;
  status: Status;
  /** Inline author object (should be extracted) */
  author: Author;
  tags?: string[];
  /** Array of inline comment objects */
  comments?: CommentsItem[];
}

export const BlogPostSchema = z.object({
  id: z.uuid(),
  title: z.string(),
  content: z.string().optional(),
  status: StatusSchema,
  author: AuthorSchema.meta({ description: "Inline author object (should be extracted)" }),
  tags: z.array(z.string()).optional(),
  comments: z.array(CommentsItemSchema).optional().meta({ description: "Array of inline comment objects" }),
}).meta({ description: "Blog post with deeply nested inline types for extraction testing" });
