// Code generated by schemagen. DO NOT EDIT.

export type Type = "email";

/**
 * Email channel configuration
 */
export interface Channel {
  subject: string;
  /**
   * @format email
   */
  to: string;
  type: Type;
}

export type Type2 = "sms";

/**
 * SMS channel configuration
 */
export interface Channel1 {
  countryCode?: string;
  phoneNumber: string;
  type: Type2;
}

export type Type3 = "push";

/**
 * Push notification configuration
 */
export interface Channel2 {
  badge?: number;
  deviceId: string;
  type: Type3;
}

export type Format = "text";

/**
 * Plain text content
 */
export interface Content {
  body: string;
  format: Format;
}

export type Format2 = "html";

/**
 * HTML content
 */
export interface Content1 {
  body: string;
  css?: string;
  format: Format2;
}

/**
 * Notification priority level
 */
export type Priority = "low" | "normal" | "high" | "urgent";

/**
 * A notification that can be sent via multiple channels
 */
export interface Notification {
  /** Unique notification ID */
  id: string;
  /**
   * When the notification was created
   * @format date-time
   */
  timestamp: string;
  /** Delivery channel configuration (email, SMS, or push) */
  channel: Channel | Channel1 | Channel2;
  /** Notification content (text or HTML) */
  content: Content | Content1;
  /** Notification priority level */
  priority?: Priority;
}
