// Code generated by schemagen. DO NOT EDIT.

package models

import (
	_ "github.com/go-playground/validator/v10"
	"time"
)

// PingPayload Payload for ping event
type PingPayload struct {
	// Ping timestamp
	Timestamp time.Time `json:"timestamp" validate:"required"`
	// Time to live in milliseconds
	Ttl int `json:"ttl" validate:"required,gte=0"`
	// Ping sequence number
	Sequence *int `json:"sequence,omitempty" validate:"gte=0"`
}