// Code generated by schemagen. DO NOT EDIT.

package models

import (
	"github.com/go-playground/validator/v10"
	"time"
)

// PongPayload Payload for pong event (minimal response)
type PongPayload struct {
	// Pong response timestamp
	Timestamp *time.Time `json:"timestamp,omitempty"`
}