// Code generated by schemagen. DO NOT EDIT.

package models

import (
	_ "github.com/go-playground/validator/v10"
)

// SubscribePayload Payload for subscribe event
type SubscribePayload struct {
	// Topic to subscribe to
	Topic string `json:"topic" validate:"required"`
	// Subscription filters
	Filters *map[string]string `json:"filters,omitempty"`
	// Quality of service level
	Qos *int `json:"qos,omitempty" validate:"gte=0,lte=2"`
}