// Code generated by schemagen. DO NOT EDIT.

package models

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/uuid"
)

// UnsubscribePayload Payload for unsubscribe event
type UnsubscribePayload struct {
	// ID of subscription to cancel
	SubscriptionId uuid.UUID `json:"subscriptionId" validate:"required,uuid"`
	// Reason for unsubscribing
	Reason *string `json:"reason,omitempty"`
}