# Code generated by schemagen. DO NOT EDIT.

from __future__ import annotations

from datetime import datetime
from enum import Enum
from uuid import UUID

from typing import Any
from pydantic import BaseModel, Field, AnyUrl


class DeliveryMode(str, Enum):
    """Delivery guarantee level"""

    AT_MOST_ONCE = "at-most-once"
    AT_LEAST_ONCE = "at-least-once"
    EXACTLY_ONCE = "exactly-once"


class Error(BaseModel):
    """API error details"""

    code: str = Field(..., description="Error code")
    message: str = Field(..., description="Human-readable error message")
    field: str | None = Field(None, description="Field that caused the error")
    details: dict[str, Any] | None = Field(None, description="Additional error context")


class Metadata(BaseModel):
    """Response metadata (inline object, not a $def)"""

    region: str | None = Field(None, description="Server region that handled the request")
    requestId: UUID = Field(..., description="Unique request identifier for tracing")
    timestamp: datetime = Field(..., description="When the response was generated")
    version: str = Field(..., description="API version")


class Pagination(BaseModel):
    """Pagination information"""

    page: int = Field(..., description="Current page number", ge=1)
    pageSize: int = Field(..., description="Items per page", ge=1, le=100)
    totalPages: int = Field(..., description="Total number of pages", ge=0)
    totalItems: int = Field(..., description="Total number of items", ge=0)
    hasNext: bool | None = Field(None, description="Whether there is a next page")
    hasPrevious: bool | None = Field(None, description="Whether there is a previous page")


class Priority(str, Enum):
    """Message priority level"""

    LOW = "low"
    NORMAL = "normal"
    HIGH = "high"
    CRITICAL = "critical"


class Message(BaseModel):
    """Message in a queue or topic"""

    id: UUID = Field(..., description="Unique message identifier")
    topic: str = Field(..., description="Message topic or queue name")
    payload: dict[str, Any] = Field(..., description="Message payload (any structure)")
    timestamp: datetime = Field(..., description="When the message was created")
    ttl: int | None = Field(None, description="Time to live in seconds", ge=0)
    retryCount: int | None = Field(None, description="Number of delivery attempts", ge=0, le=10)
    priority: Priority | None = Field(None, description="Message priority level")


class Subscription(BaseModel):
    """Subscription to a topic"""

    id: UUID
    topic: str = Field(..., description="Topic pattern to subscribe to")
    filters: dict[str, str] | None = Field(None, description="Message filtering rules")
    deliveryMode: DeliveryMode = Field(..., description="Delivery guarantee level")
    endpoint: AnyUrl | None = Field(None, description="Webhook URL for message delivery")


class Throughput(BaseModel):
    """Nested inline object"""

    bytesPerSecond: float | None = Field(None, ge=0)
    messagesPerSecond: float | None = Field(None, ge=0)


class Stats(BaseModel):
    """Queue statistics (inline object)"""

    activeSubscriptions: int | None = Field(None, ge=0)
    pendingMessages: int | None = Field(None, ge=0)
    throughput: Throughput | None = Field(None, description="Nested inline object")
    totalMessages: int | None = Field(None, ge=0)


class MessagingAPI(BaseModel):
    """Real-world messaging API with pagination, errors, and message queue concepts"""

    messages: list[Message] | None = Field(None, description="List of messages")
    subscriptions: list[Subscription] | None = Field(None, description="Active subscriptions")
    pagination: Pagination | None = None
    errors: list[Error] | None = Field(None, description="Any errors encountered")
    metadata: Metadata = Field(..., description="Response metadata (inline object, not a $def)")
    stats: Stats | None = Field(None, description="Queue statistics (inline object)")
