// Code generated by schemagen. DO NOT EDIT.

/**
 * Additional properties patterns
 */
export interface AdditionalProps {
  /** Any additional properties allowed */
  flexible?: Flexible;
  /** No additional properties allowed */
  strict?: Strict;
  /** Additional properties must be numbers */
  typedMap?: TypedMap;
}

export interface Arrays {
  /** Array with size constraints */
  minMaxArray?: string[];
}

/**
 * Array types
 */
export interface Arrays2 {
  /** Array of numbers */
  numberArray?: number[];
  /** Array of objects */
  objectArray?: ObjectArrayItem[];
  /** Array of strings */
  stringArray?: string[];
}

/**
 * Validation constraints
 */
export interface Constraints {
  arrays?: Arrays;
  numbers?: Numbers;
  strings?: Strings;
}

/**
 * Edge cases: reserved keywords and special characters
 */
export interface EdgeCases {
  /** Empty object with no properties */
  emptyConfig?: Record<string, any>;
  /** Reserved keywords in TypeScript and Python */
  reservedKeywords?: ReservedKeywords;
  /** Special characters in property names */
  specialChars?: SpecialChars;
}

/**
 * Enumeration types
 */
export interface Enums {
  /** Mixed type enumeration */
  mixedEnum?: MixedEnum;
  /** Number enumeration */
  numberEnum?: NumberEnum;
  /** String enumeration */
  stringEnum?: StringEnum;
}

/**
 * Any additional properties allowed
 */
export interface Flexible {
  enabled?: boolean;
  version: string;
}

/**
 * String formats for validation
 */
export interface Formats {
  /**
   * Date only (YYYY-MM-DD)
   * @format date
   */
  date?: string;
  /**
   * Full timestamp with timezone
   * @format date-time
   */
  dateTime?: string;
  /**
   * User email address
   * @format email
   */
  email?: string;
  /**
   * IPv4 address
   * @format ipv4
   */
  ipv4?: string;
  /**
   * IPv6 address
   * @format ipv6
   */
  ipv6?: string;
  /**
   * Time only (HH:MM:SS)
   * @format time
   */
  time?: string;
  /**
   * Resource URL
   * @format uri
   */
  uri?: string;
  /**
   * Unique identifier
   * @format uuid
   */
  uuid?: string;
}

/**
 * Comprehensive test of all basic types, formats, constraints, and edge cases
 */
export interface Foundation {
  /** All primitive types */
  primitives: Primitives;
  /** String formats for validation */
  formats?: Formats;
  /** Validation constraints */
  constraints?: Constraints;
  /** Enumeration types */
  enums?: Enums;
  /** Array types */
  arrays?: Arrays2;
  /** Nested object structure */
  nested?: Nested;
  /** Required vs optional fields */
  nullable?: Nullable;
  /** Additional properties patterns */
  additionalProps?: AdditionalProps;
  /** Edge cases: reserved keywords and special characters */
  edgeCases?: EdgeCases;
}

export interface Level1 {
  level2?: Level2;
}

export interface Level2 {
  /** Three levels deep */
  level3?: string;
}

/**
 * Mixed type enumeration
 */
export type MixedEnum = "string" | 42 | true | null;

/**
 * Nested object structure
 */
export interface Nested {
  level1?: Level1;
}

/**
 * Required vs optional fields
 */
export interface Nullable {
  optionalArray?: string[];
  optionalNumber?: number;
  optionalObject?: OptionalObject;
  /** This field is optional */
  optionalString?: string;
  /** This field is required */
  requiredString: string;
}

/**
 * Number enumeration
 */
export enum NumberEnum {
  N_1 = 1,
  N_2 = 2,
  N_3 = 3
}

export interface Numbers {
  /** Number with exclusive bounds */
  exclusiveRange?: number;
  /** Integer with constraints */
  minMaxInteger?: number;
  /** Number with inclusive bounds */
  minMaxNumber?: number;
}

export interface ObjectArrayItem {
  id?: string;
  value?: number;
}

export interface OptionalObject {
  field?: string;
}

/**
 * All primitive types
 */
export interface Primitives {
  booleanVal: boolean;
  integerVal: number;
  numberVal: number;
  stringVal: string;
}

/**
 * Reserved keywords in TypeScript and Python
 */
export interface ReservedKeywords {
  as?: string;
  async?: string;
  await?: string;
  class?: string;
  def?: string;
  export?: string;
  from?: string;
  import?: string;
  interface?: string;
  lambda?: string;
  return?: string;
  type?: string;
  yield?: string;
}

/**
 * Special characters in property names
 */
export interface SpecialChars {
  $dollar?: string;
  "123numeric"?: string;
  "@special"?: string;
  PascalCase?: string;
  camelCase?: string;
  "kebab-case"?: string;
  snake_case?: string;
  "with spaces"?: string;
  "with.dots"?: string;
}

/**
 * No additional properties allowed
 */
export interface Strict {
  id: string;
  name?: string;
}

/**
 * String enumeration
 */
export type StringEnum = "option1" | "option2" | "option3";

export interface Strings {
  /** String with length constraints */
  minMaxString?: string;
  /** String matching regex pattern */
  patternString?: string;
}

/**
 * Additional properties must be numbers
 */
export interface TypedMap {
  source?: string;
  timestamp: string;
}
