// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

export interface Entity {
  /**
   * @format uuid
   */
  id: string;
}

export const EntitySchema = z.object({
  id: z.uuid(),
});

export interface Auditable {
  createdBy: string;
  /**
   * @format date-time
   */
  createdAt: string;
  /**
   * @format date-time
   */
  updatedAt?: string;
}

export const AuditableSchema = z.object({
  createdBy: z.string(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime().optional(),
});

/**
 * Document with multiple mixins - tests allOf with refs, inline objects, and field deduplication
 */
export type Document = Entity & Auditable & {
  /** First title definition */
  title: string;
  content: string;
  author?: string;
  tags?: string[];
};

export const DocumentSchema = EntitySchema.merge(AuditableSchema).extend({
  title: z.string().meta({ description: "First title definition" }),
  content: z.string(),
  author: z.string().optional(),
  tags: z.array(z.string()).optional(),
}).meta({ description: "Document with multiple mixins - tests allOf with refs, inline objects, and field deduplication" });
