// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

export interface IdObject {
  /**
   * @format uuid
   */
  id: string;
}

export const IdObjectSchema = z.object({
  id: z.uuid(),
});

export interface Timestamped {
  /**
   * @format date-time
   */
  createdAt: string;
  /**
   * @format date-time
   */
  updatedAt?: string;
}

export const TimestampedSchema = z.object({
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime().optional(),
});

export interface Person {
  /**
   * @format email
   */
  email?: string;
  name?: string;
}

export const PersonSchema = z.object({
  email: z.email().optional(),
  name: z.string().optional(),
});

export interface Node {
  value?: string;
  next?: Node;
}

export const NodeSchema = z.object({
  value: z.string().optional(),
  get next() { return NodeSchema.optional() },
});

export type Status = "active" | "paused" | any;

export const StatusSchema = z.union([
  z.literal("active"),
  z.literal("paused"),
  z.object({ complex: z.literal(true) }).strict(),
]);

export interface Payload {
  data: string;
  type: "A";
}

export const PayloadSchema = z.object({
  data: z.string(),
  type: z.enum(["A"]),
});

export interface Payload1 {
  data: number;
  type: "B";
}

export const Payload1Schema = z.object({
  data: z.number(),
  type: z.enum(["B"]),
});

/**
 * One schema to test everything
 */
export type MegaTest = IdObject & Timestamped & {
  tags: string[];
  owner?: Person;
  status: Status;
  meta?: Record<string, string>;
  payload?: Payload | Payload1;
  node?: Node;
};

export const MegaTestSchema = IdObjectSchema.merge(TimestampedSchema).extend({
  tags: z.array(z.string()).min(1),
  owner: PersonSchema.optional(),
  status: StatusSchema,
  meta: z.record(z.string(), z.string()).optional(),
  payload: z.union([PayloadSchema, Payload1Schema]).optional(),
  node: NodeSchema.optional(),
}).meta({ description: "One schema to test everything" });
