# Code generated by schemagen. DO NOT EDIT.

from __future__ import annotations

from pydantic import BaseModel

from .settings import Settings


class Config(BaseModel):
    """Application configuration (YAML format test)"""

    appName: str
    settings: Settings | None = None
    version: str
