# Code generated by schemagen. DO NOT EDIT.

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


class LogLevel(str, Enum):
    DEBUG = "debug"
    INFO = "info"
    WARN = "warn"
    ERROR = "error"


class Settings(BaseModel):
    """Application settings"""

    debug: bool | None = None
    logLevel: LogLevel | None = None
    maxConnections: int | None = Field(None, ge=1)
