// Code generated by schemagen. DO NOT EDIT.

export interface Auditable {
  createdBy: string;
  /**
   * @format date-time
   */
  createdAt: string;
  /**
   * @format date-time
   */
  updatedAt?: string;
}

/**
 * Document with multiple mixins - tests allOf with refs, inline objects, and field deduplication
 */
export type Document = Entity & Auditable & {
  /** First title definition */
  title: string;
  content: string;
  author?: string;
  tags?: string[];
};

export interface Entity {
  /**
   * @format uuid
   */
  id: string;
}
