// Code generated by schemagen. DO NOT EDIT.

import type { EventHeader } from './header';
import type { EventMetadata } from './meta';
import type { PingPayload } from './payloads/ping';
import type { PongPayload } from './payloads/pong';
import type { SubscribePayload } from './payloads/subscribe';
import type { UnsubscribePayload } from './payloads/unsubscribe';

/**
 * Main event schema with external references
 */
export interface Event {
  /** Event header (external ref without fragment) */
  header: EventHeader;
  /** Event metadata (external ref without fragment) */
  meta: EventMetadata;
  /** Event payload (varies by event type) */
  payload: SubscribePayload | UnsubscribePayload | PingPayload | PongPayload;
}
