// Code generated by schemagen. DO NOT EDIT.

/**
 * Type of event
 */
export type EventType = "subscribe" | "unsubscribe" | "ping" | "pong";

/**
 * Standard event header with metadata
 */
export interface EventHeader {
  /**
   * Unique event identifier
   * @format uuid
   */
  id: string;
  type: EventType;
  /**
   * When the event occurred
   * @format date-time
   */
  timestamp: string;
  /**
   * Event source system
   * @format uri
   */
  source: string;
}
