// Code generated by schemagen. DO NOT EDIT.

package models

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/uuid"
	"time"
)

type Entity struct {
	Id uuid.UUID `json:"id" validate:"required,uuid"`
}

type Auditable struct {
	CreatedBy string `json:"createdBy" validate:"required"`
	CreatedAt time.Time `json:"createdAt" validate:"required"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// Document Document with multiple mixins - tests allOf with refs, inline objects, and field deduplication
type Document struct {
	Entity
	Auditable
	// First title definition
	Title string `json:"title" validate:"required"`
	Content string `json:"content" validate:"required"`
	Author *string `json:"author,omitempty"`
	Tags *[]string `json:"tags,omitempty"`
}