// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

export const StatusSchema = z.enum(["draft", "published", "archived"]);

export type Status = z.infer<typeof StatusSchema>;

export const RoleSchema = z.enum(["admin", "editor", "contributor"]);

export type Role = z.infer<typeof RoleSchema>;

/**
 * Inline author object (should be extracted)
 */
export const AuthorSchema = z.object({
  email: z.email(),
  name: z.string(),
  role: RoleSchema.optional(),
}).meta({ description: "Inline author object (should be extracted)" });

export type Author = z.infer<typeof AuthorSchema>;

/**
 * Nested inline commenter object (should be extracted)
 */
export const CommenterSchema = z.object({
  email: z.email(),
  name: z.string(),
}).meta({ description: "Nested inline commenter object (should be extracted)" });

export type Commenter = z.infer<typeof CommenterSchema>;

/**
 * Inline comment object (should be extracted)
 */
export const CommentsItemSchema = z.object({
  commenter: CommenterSchema.meta({ description: "Nested inline commenter object (should be extracted)" }),
  id: z.uuid(),
  text: z.string(),
}).meta({ description: "Inline comment object (should be extracted)" });

export type CommentsItem = z.infer<typeof CommentsItemSchema>;

/**
 * Blog post with deeply nested inline types for extraction testing
 */
export const BlogPostSchema = z.object({
  id: z.uuid(),
  title: z.string(),
  content: z.string().optional(),
  status: StatusSchema,
  author: AuthorSchema.meta({ description: "Inline author object (should be extracted)" }),
  tags: z.array(z.string()).optional(),
  comments: z.array(CommentsItemSchema).optional().meta({ description: "Array of inline comment objects" }),
}).meta({ description: "Blog post with deeply nested inline types for extraction testing" });

export type BlogPost = z.infer<typeof BlogPostSchema>;
