// Code generated by schemagen. DO NOT EDIT.

/**
 * Address with country reference
 */
export interface Address {
  street: string;
  city: string;
  zipCode?: string;
  /** Reference to Country */
  country: Country;
}

export type Code = "US" | "CA" | "UK" | "FR" | "DE" | "JP";

/**
 * Country information
 */
export interface Country {
  name: string;
  code: Code;
}

/**
 * Office with address reference
 */
export interface Office {
  name: string;
  /** Reference to Address (which references Country) */
  address: Address;
  employees?: number;
}

/**
 * Organization schema with chained internal references
 */
export interface Organization {
  /**
   * @format uuid
   */
  id: string;
  name: string;
  /** Main office (references Office → Address → Country) */
  headquarters: Office;
  /** Branch offices (reuses Office type multiple times) */
  branches?: Office[];
}
