# Code generated by schemagen. DO NOT EDIT.

from __future__ import annotations

from pydantic import BaseModel, Field


class CyclicRef(BaseModel):
    """Type with cyclic reference to itself"""

    id: str = Field(..., description="Unique identifier")
    name: str | None = None
    parent: CyclicRef | None = Field(None, description="Reference to parent node (cyclic)")
    children: list[CyclicRef] | None = Field(None, description="Child nodes (cyclic)")
