# Code generated by schemagen. DO NOT EDIT.

from __future__ import annotations

from pydantic import BaseModel, Field


class DescriptionQuotes(BaseModel):
    """This has "double quotes" and '''triple single''' and \"\"\"triple double\"\"\" quotes"""

    field: str | None = Field(None, description='Field with "quotes" and \\backslash in description')
