# Code generated by schemagen. DO NOT EDIT.

from __future__ import annotations

from typing import Literal


# Enum with complex values (objects/arrays) - all preserved in output
EnumComplex = Literal["simple", 42]
