# Code generated by schemagen. DO NOT EDIT.

from __future__ import annotations

from pydantic import BaseModel, Field


class SpecialProps(BaseModel):
    """Object with special property names requiring aliases"""

    kebab_case: str = Field(..., alias="kebab-case", description="Property with kebab-case name")
    with_spaces: str | None = Field(None, alias="with spaces", description="Property with spaces")
    field_123numeric: int | None = Field(None, alias="123numeric", description="Property starting with number")
    field__dollar: bool | None = Field(None, alias="$dollar", description="Property starting with dollar")
    class_: str | None = Field(None, alias="class", description="Python reserved keyword")
    from_: str | None = Field(None, alias="from", description="Python reserved keyword")
