// Code generated by schemagen. DO NOT EDIT.

/**
 * Email channel configuration
 */
export interface Channel {
  subject: string;
  /**
   * @format email
   */
  to: string;
  type: "email";
}

/**
 * SMS channel configuration
 */
export interface Channel1 {
  countryCode?: string;
  phoneNumber: string;
  type: "sms";
}

/**
 * Push notification configuration
 */
export interface Channel2 {
  badge?: number;
  deviceId: string;
  type: "push";
}

/**
 * Plain text content
 */
export interface Content {
  body: string;
  format: "text";
}

/**
 * HTML content
 */
export interface Content1 {
  body: string;
  css?: string;
  format: "html";
}

/**
 * A notification that can be sent via multiple channels
 */
export interface Notification {
  /** Unique notification ID */
  id: string;
  /**
   * When the notification was created
   * @format date-time
   */
  timestamp: string;
  /** Delivery channel configuration (email, SMS, or push) */
  channel: Channel | Channel1 | Channel2;
  /** Notification content (text or HTML) */
  content: Content | Content1;
  /** Notification priority level */
  priority?: "low" | "normal" | "high" | "urgent";
}
