package common

import (
	"fmt"
	"strings"
	"time"
)

// CommentPrefix represents a language-specific comment prefix.
type CommentPrefix string

const (
	// CommentPrefixTypeScript represents TypeScript/JavaScript comments (//)
	CommentPrefixTypeScript CommentPrefix = "//"
	// CommentPrefixPython represents Python comments (#)
	CommentPrefixPython CommentPrefix = "#"
	// CommentPrefixGo represents Go comments (//)
	CommentPrefixGo CommentPrefix = "//"
)

// HeaderConfig defines file header settings.
type HeaderConfig struct {
	CommentPrefix    CommentPrefix
	DisableHeaders   bool
	DisableTimestamp bool
}

// GenerateHeader creates a file header comment.
func GenerateHeader(cfg HeaderConfig) string {
	if cfg.DisableHeaders {
		return ""
	}

	var sb strings.Builder
	prefix := string(cfg.CommentPrefix) + " "

	sb.WriteString(prefix)
	sb.WriteString("Code generated by schemagen. DO NOT EDIT.\n")

	if !cfg.DisableTimestamp {
		timestamp := time.Now().UTC().Format(time.RFC3339)
		sb.WriteString(prefix)
		sb.WriteString(fmt.Sprintf("  timestamp: %s\n", timestamp))
	}

	sb.WriteString("\n")
	return sb.String()
}
