package common

import (
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
)

func fixedTimeFn(t time.Time) func() time.Time {
	return func() time.Time {
		return t
	}
}

func TestGenerateHeader(t *testing.T) {
	fixedTime := time.Date(2025, 1, 1, 12, 0, 0, 0, time.UTC)

	tests := []struct {
		name   string
		cfg    HeaderConfig
		now    func() time.Time
		expect string
	}{
		{
			name: "slash prefix with timestamp",
			cfg: HeaderConfig{
				CommentPrefix:    CommentPrefixSlash,
				DisableHeaders:   false,
				DisableTimestamp: false,
			},
			now: fixedTimeFn(fixedTime),
			expect: "// Code generated by schemagen. DO NOT EDIT.\n" +
				"//   timestamp: 2025-01-01T12:00:00Z\n\n",
		},
		{
			name: "hash prefix without timestamp",
			cfg: HeaderConfig{
				CommentPrefix:    CommentPrefixHash,
				DisableHeaders:   false,
				DisableTimestamp: true,
			},
			now:    fixedTimeFn(fixedTime),
			expect: "# Code generated by schemagen. DO NOT EDIT.\n\n",
		},
		{
			name: "headers disabled",
			cfg: HeaderConfig{
				CommentPrefix:  CommentPrefixSlash,
				DisableHeaders: true,
			},
			now:    fixedTimeFn(fixedTime),
			expect: "",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := generateHeader(tt.cfg, tt.now)
			assert.Equal(t, tt.expect, result)
		})
	}
}
