package common

import (
	"strings"
	"time"
)

// CommentPrefix represents a comment prefix (e.g. // or #).
type CommentPrefix string

const (
	CommentPrefixSlash CommentPrefix = "//"
	CommentPrefixHash  CommentPrefix = "#"
)

// HeaderConfig defines file header settings.
type HeaderConfig struct {
	CommentPrefix    CommentPrefix
	DisableHeaders   bool
	DisableTimestamp bool
}

// GenerateHeader creates a file header comment.
func GenerateHeader(cfg HeaderConfig) string {
	return generateHeader(cfg, time.Now)
}

func generateHeader(cfg HeaderConfig, now func() time.Time) string {
	if cfg.DisableHeaders {
		return ""
	}

	var sb strings.Builder
	linePrefix := string(cfg.CommentPrefix) + " "

	sb.WriteString(linePrefix)
	sb.WriteString("Code generated by schemagen. DO NOT EDIT.\n")

	if !cfg.DisableTimestamp {
		sb.WriteString(linePrefix)
		sb.WriteString("  timestamp: ")
		sb.WriteString(now().UTC().Format(time.RFC3339))
		sb.WriteString("\n")
	}

	sb.WriteString("\n")
	return sb.String()
}
