package output

import (
	"path/filepath"
	"sort"
	"strings"

	"github.com/mirpo/schemagen/pkg/constants"
)

func GenerateBarrelFiles(plan *OutputPlan, language string) []BarrelFile {
	if language == constants.LanguageGoShort || language == string(constants.LanguageGo) {
		return []BarrelFile{}
	}

	dirFiles := groupFilesByDirectory(plan.Files)

	var barrels []BarrelFile

	for dir, files := range dirFiles {
		barrel := generateBarrelForDirectory(dir, files, language)
		if barrel != nil {
			barrels = append(barrels, *barrel)
		}
	}

	sort.Slice(barrels, func(i, j int) bool {
		return barrels[i].Path < barrels[j].Path
	})

	return barrels
}

func groupFilesByDirectory(files []OutputFile) map[string][]OutputFile {
	dirFiles := make(map[string][]OutputFile)

	for _, file := range files {
		dir := filepath.Dir(file.RelativePath)
		if dir == "." {
			dir = ""
		}

		dirFiles[dir] = append(dirFiles[dir], file)
	}

	return dirFiles
}

func generateBarrelForDirectory(dir string, files []OutputFile, language string) *BarrelFile {
	if len(files) == 0 {
		return nil
	}

	var barrelPath string
	switch language {
	case constants.LanguageTypeScriptShort, string(constants.LanguageTypeScript):
		if dir == "" {
			barrelPath = "index.ts"
		} else {
			barrelPath = filepath.Join(dir, "index.ts")
		}
	case constants.LanguagePythonShort, string(constants.LanguagePython):
		if dir == "" {
			barrelPath = "__init__.py"
		} else {
			barrelPath = filepath.Join(dir, "__init__.py")
		}
	default:
		return nil
	}

	exports := make([]string, 0, len(files))
	for _, file := range files {
		fileName := filepath.Base(file.RelativePath)
		nameWithoutExt := fileName[:len(fileName)-len(filepath.Ext(fileName))]

		if nameWithoutExt == "index" || nameWithoutExt == "__init__" {
			continue
		}

		exports = append(exports, nameWithoutExt)
	}

	sort.Strings(exports)

	return &BarrelFile{
		Path:    barrelPath,
		Exports: exports,
	}
}

func GenerateBarrelContent(barrel BarrelFile, language string) string {
	switch language {
	case constants.LanguageTypeScriptShort, string(constants.LanguageTypeScript):
		return generateTypeScriptBarrel(barrel)
	case constants.LanguagePythonShort, string(constants.LanguagePython):
		return generatePythonBarrel(barrel)
	}
	return ""
}

func generateTypeScriptBarrel(barrel BarrelFile) string {
	var lines []string
	lines = append(lines, "// Code generated by schemagen. DO NOT EDIT.")
	lines = append(lines, "")

	for _, export := range barrel.Exports {
		lines = append(lines, "export * from './"+export+"';")
	}

	lines = append(lines, "")
	return strings.Join(lines, "\n")
}

func generatePythonBarrel(barrel BarrelFile) string {
	var lines []string
	lines = append(lines, "# Code generated by schemagen. DO NOT EDIT.")
	lines = append(lines, "")

	for _, export := range barrel.Exports {
		lines = append(lines, "from ."+export+" import *")
	}

	lines = append(lines, "")

	return strings.Join(lines, "\n")
}

func CollectAllDirectories(files []OutputFile) []string {
	dirSet := make(map[string]bool)

	for _, file := range files {
		levels := GetDirectoryLevels(file.RelativePath)
		for _, level := range levels {
			dirSet[level] = true
		}

		dir := filepath.Dir(file.RelativePath)
		if dir != "." && dir != "" {
			dirSet[dir] = true
		}
	}

	dirs := make([]string, 0, len(dirSet))
	for dir := range dirSet {
		dirs = append(dirs, dir)
	}

	sort.Strings(dirs)
	return dirs
}

func GenerateNestedBarrels(files []OutputFile, language string) []BarrelFile {
	if language == constants.LanguageGoShort || language == string(constants.LanguageGo) {
		return []BarrelFile{}
	}

	dirs := CollectAllDirectories(files)

	dirFiles := groupFilesByDirectory(files)

	var barrels []BarrelFile

	for _, dir := range dirs {
		filesInDir := dirFiles[dir]

		var exports []string

		for _, file := range filesInDir {
			fileName := filepath.Base(file.RelativePath)
			nameWithoutExt := fileName[:len(fileName)-len(filepath.Ext(fileName))]
			exports = append(exports, nameWithoutExt)
		}

		subdirs := getImmediateSubdirs(dir, dirs)
		exports = append(exports, subdirs...)

		sort.Strings(exports)

		var barrelPath string
		switch language {
		case constants.LanguageTypeScriptShort, string(constants.LanguageTypeScript):
			if dir == "" {
				barrelPath = "index.ts"
			} else {
				barrelPath = filepath.Join(dir, "index.ts")
			}
		case constants.LanguagePythonShort, string(constants.LanguagePython):
			if dir == "" {
				barrelPath = "__init__.py"
			} else {
				barrelPath = filepath.Join(dir, "__init__.py")
			}
		}

		if barrelPath != "" {
			barrels = append(barrels, BarrelFile{
				Path:    barrelPath,
				Exports: exports,
			})
		}
	}

	if len(files) > 0 {
		rootFiles := dirFiles[""]

		var rootExports []string
		for _, file := range rootFiles {
			fileName := filepath.Base(file.RelativePath)
			nameWithoutExt := fileName[:len(fileName)-len(filepath.Ext(fileName))]
			rootExports = append(rootExports, nameWithoutExt)
		}

		topLevelDirs := getTopLevelDirs(dirs)
		rootExports = append(rootExports, topLevelDirs...)

		sort.Strings(rootExports)

		var rootBarrelPath string
		switch language {
		case constants.LanguageTypeScriptShort, string(constants.LanguageTypeScript):
			rootBarrelPath = "index.ts"
		case constants.LanguagePythonShort, string(constants.LanguagePython):
			rootBarrelPath = "__init__.py"
		}

		if rootBarrelPath != "" && len(rootExports) > 0 {
			barrels = append([]BarrelFile{{
				Path:    rootBarrelPath,
				Exports: rootExports,
			}}, barrels...)
		}
	}

	return barrels
}

func getImmediateSubdirs(parentDir string, allDirs []string) []string {
	var subdirs []string

	for _, dir := range allDirs {
		if dir == parentDir {
			continue
		}

		if parentDir == "" {
			if !strings.Contains(dir, string(filepath.Separator)) {
				subdirs = append(subdirs, filepath.Base(dir))
			}
		} else if strings.HasPrefix(dir, parentDir+string(filepath.Separator)) {
			relPath := strings.TrimPrefix(dir, parentDir+string(filepath.Separator))
			if !strings.Contains(relPath, string(filepath.Separator)) {
				subdirs = append(subdirs, filepath.Base(dir))
			}
		}
	}

	return subdirs
}

func getTopLevelDirs(allDirs []string) []string {
	var topLevel []string

	for _, dir := range allDirs {
		if !strings.Contains(dir, string(filepath.Separator)) {
			topLevel = append(topLevel, dir)
		}
	}

	return topLevel
}
