package output

import (
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestGenerateBarrelFiles_TypeScript(t *testing.T) {
	plan := &OutputPlan{
		Files: []OutputFile{
			{RelativePath: "event.ts"},
			{RelativePath: "header.ts"},
			{RelativePath: "meta.ts"},
		},
	}

	barrels := GenerateBarrelFiles(plan, "ts")

	require.Len(t, barrels, 1, "should generate exactly 1 barrel file")
	assert.Equal(t, "index.ts", barrels[0].Path, "barrel path should be index.ts")

	expectedExports := []string{"event", "header", "meta"}
	require.Len(t, barrels[0].Exports, len(expectedExports), "should have expected number of exports")

	for i, expected := range expectedExports {
		assert.Equal(t, expected, barrels[0].Exports[i], "export should match")
	}
}

func TestGenerateBarrelFiles_Python(t *testing.T) {
	plan := &OutputPlan{
		Files: []OutputFile{
			{RelativePath: "user.py"},
			{RelativePath: "role.py"},
		},
	}

	barrels := GenerateBarrelFiles(plan, "py")

	require.Len(t, barrels, 1, "should generate exactly 1 barrel file")
	assert.Equal(t, "__init__.py", barrels[0].Path, "barrel path should be __init__.py")

	expectedExports := []string{"role", "user"}
	for i, expected := range expectedExports {
		assert.Equal(t, expected, barrels[0].Exports[i], "export should match")
	}
}

func TestGenerateBarrelFiles_Go_Empty(t *testing.T) {
	plan := &OutputPlan{
		Files: []OutputFile{
			{RelativePath: "user.go"},
		},
	}

	barrels := GenerateBarrelFiles(plan, "go")

	assert.Empty(t, barrels, "should not generate barrels for Go")
}

func TestGenerateBarrelFiles_Nested(t *testing.T) {
	plan := &OutputPlan{
		Files: []OutputFile{
			{RelativePath: filepath.Join("events", "event.ts")},
			{RelativePath: filepath.Join("events", "header.ts")},
			{RelativePath: filepath.Join("events", "payloads", "subscribe.ts")},
			{RelativePath: filepath.Join("events", "payloads", "ping.ts")},
		},
	}

	barrels := GenerateBarrelFiles(plan, "ts")

	require.Len(t, barrels, 2, "should generate exactly 2 barrel files")

	foundEventsBarrel := false
	foundPayloadsBarrel := false

	for _, barrel := range barrels {
		if barrel.Path == filepath.Join("events", "index.ts") {
			foundEventsBarrel = true
			assert.Len(t, barrel.Exports, 2, "events/index.ts should have 2 exports")
		}
		if barrel.Path == filepath.Join("events", "payloads", "index.ts") {
			foundPayloadsBarrel = true
			assert.Len(t, barrel.Exports, 2, "events/payloads/index.ts should have 2 exports")
		}
	}

	assert.True(t, foundEventsBarrel, "should find events/index.ts")
	assert.True(t, foundPayloadsBarrel, "should find events/payloads/index.ts")
}

func TestGenerateTypeScriptBarrel(t *testing.T) {
	barrel := BarrelFile{
		Path:    "index.ts",
		Exports: []string{"event", "header", "meta"},
	}

	content := generateTypeScriptBarrel(barrel)

	expectedLines := []string{
		"// Code generated by schemagen. DO NOT EDIT.",
		"",
		"export * from './event';",
		"export * from './header';",
		"export * from './meta';",
		"",
	}

	lines := strings.Split(content, "\n")

	require.Len(t, lines, len(expectedLines), "should have expected number of lines")

	for i, expected := range expectedLines {
		assert.Equal(t, expected, lines[i], "line content should match")
	}
}

func TestGeneratePythonBarrel(t *testing.T) {
	barrel := BarrelFile{
		Path:    "__init__.py",
		Exports: []string{"user", "role"},
	}

	content := generatePythonBarrel(barrel)

	expectedLines := []string{
		"# Code generated by schemagen. DO NOT EDIT.",
		"",
		"from .user import *",
		"from .role import *",
		"",
	}

	lines := strings.Split(content, "\n")

	require.Len(t, lines, len(expectedLines), "should have expected number of lines")

	for i, expected := range expectedLines {
		assert.Equal(t, expected, lines[i], "line content should match")
	}
}

func TestCollectAllDirectories(t *testing.T) {
	files := []OutputFile{
		{RelativePath: "event.ts"},
		{RelativePath: filepath.Join("events", "header.ts")},
		{RelativePath: filepath.Join("events", "payloads", "v1", "subscribe.ts")},
		{RelativePath: filepath.Join("events", "payloads", "v2", "ping.ts")},
	}

	dirs := CollectAllDirectories(files)

	expectedDirs := []string{
		"events",
		filepath.Join("events", "payloads"),
		filepath.Join("events", "payloads", "v1"),
		filepath.Join("events", "payloads", "v2"),
	}

	require.Len(t, dirs, len(expectedDirs), "should collect expected number of directories")

	for i, expected := range expectedDirs {
		expectedNorm := filepath.FromSlash(expected)
		assert.Equal(t, expectedNorm, dirs[i], "directory should match")
	}
}

func TestGroupFilesByDirectory(t *testing.T) {
	files := []OutputFile{
		{RelativePath: "user.ts"},
		{RelativePath: "role.ts"},
		{RelativePath: filepath.Join("events", "event.ts")},
		{RelativePath: filepath.Join("events", "header.ts")},
	}

	dirFiles := groupFilesByDirectory(files)

	require.Len(t, dirFiles, 2, "should group into 2 directories")
	assert.Len(t, dirFiles[""], 2, "root should have 2 files")
	assert.Len(t, dirFiles["events"], 2, "events directory should have 2 files")
}

func TestGenerateBarrelForDirectory_EmptyFiles(t *testing.T) {
	barrel := generateBarrelForDirectory("events", []OutputFile{}, "ts")

	assert.Nil(t, barrel, "should return nil barrel for empty files")
}

func TestGenerateBarrelForDirectory_SkipBarrelFiles(t *testing.T) {
	files := []OutputFile{
		{RelativePath: "event.ts"},
		{RelativePath: "index.ts"},
	}

	barrel := generateBarrelForDirectory("", files, "ts")

	require.NotNil(t, barrel, "should generate barrel")
	require.Len(t, barrel.Exports, 1, "index.ts should be skipped")
	assert.Equal(t, "event", barrel.Exports[0], "should export only event")
}

func TestGenerateNestedBarrels(t *testing.T) {
	files := []OutputFile{
		{RelativePath: "root.ts"},
		{RelativePath: filepath.Join("a", "file1.ts")},
		{RelativePath: filepath.Join("a", "b", "file2.ts")},
	}

	barrels := GenerateNestedBarrels(files, "ts")

	foundRoot := false
	foundA := false
	foundAB := false

	for _, barrel := range barrels {
		if barrel.Path == "index.ts" {
			foundRoot = true
		}
		if barrel.Path == filepath.Join("a", "index.ts") {
			foundA = true
		}
		if barrel.Path == filepath.Join("a", "b", "index.ts") {
			foundAB = true
		}
	}

	assert.True(t, foundRoot, "should find root index.ts")
	assert.True(t, foundA, "should find a/index.ts")
	assert.True(t, foundAB, "should find a/b/index.ts")
}
