# Code generated by schemagen. DO NOT EDIT.

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, Field


class Auditable(BaseModel):
    createdBy: str
    createdAt: datetime
    updatedAt: datetime | None = None


class Entity(BaseModel):
    id: UUID


class Document(Entity, Auditable):
    """Document with multiple mixins - tests allOf with refs, inline objects, and field deduplication"""

    title: str = Field(..., description="First title definition")
    content: str
    author: str | None = None
    tags: list[str] | None = None
