# Code generated by schemagen. DO NOT EDIT.

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from typing import Literal
from pydantic import BaseModel, Field, EmailStr


class IdObject(BaseModel):
    id: UUID


class Node(BaseModel):
    value: str | None = None
    next: Node | None = None


class Payload(BaseModel):
    data: str
    type: Literal["A"]


class Payload1(BaseModel):
    data: float
    type: Literal["B"]


class Person(BaseModel):
    email: EmailStr | None = None
    name: str | None = None


Status = Literal["active", "paused"]


class Timestamped(BaseModel):
    createdAt: datetime
    updatedAt: datetime | None = None


class MegaTest(IdObject, Timestamped):
    """One schema to test everything"""

    tags: list[str] = Field(..., min_length=1)
    owner: Person | None = None
    status: Status
    meta: dict[str, str] | None = None
    payload: Payload | Payload1 | None = None
    node: Node | None = None
