package generation

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/kaptinlin/jsonschema"
	"github.com/mirpo/schemagen/pkg/output"
	"github.com/mirpo/schemagen/pkg/schema"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

/*
 Helpers
*/

func createTestCompiler(t *testing.T) *jsonschema.Compiler {
	t.Helper()

	compiler := jsonschema.NewCompiler()
	schemaJSON := []byte(`{
		"type": "object",
		"title": "User",
		"properties": {
			"name": {"type": "string"},
			"age": {"type": "integer"}
		},
		"required": ["name"]
	}`)

	_, err := compiler.Compile(schemaJSON, "test.json")
	require.NoError(t, err)

	return compiler
}

func createTestSchema(t *testing.T, name string) *schema.Schema {
	t.Helper()

	compiler := createTestCompiler(t)
	compiled, err := compiler.Compile([]byte(`{
		"type": "object",
		"title": "`+name+`",
		"properties": {
			"id": {"type": "string"}
		}
	}`), "test.json")
	require.NoError(t, err)

	return &schema.Schema{
		Name:         name,
		Path:         "test.json",
		RelativePath: "test.json",
		Compiled:     compiled,
	}
}

/*
 validateConfig
*/

func TestValidateConfig(t *testing.T) {
	validCompiler := createTestCompiler(t)
	validSchema := createTestSchema(t, "User")

	tests := []struct {
		name    string
		cfg     *Config
		wantErr bool
	}{
		{"nil config", nil, true},
		{"no schemas", &Config{}, true},
		{
			"missing compiler",
			&Config{
				Schemas:  []*schema.Schema{validSchema},
				OutDir:   "/tmp",
				Language: LanguageTypeScript,
			},
			true,
		},
		{
			"missing outdir",
			&Config{
				Schemas:  []*schema.Schema{validSchema},
				Compiler: validCompiler,
				Language: LanguageTypeScript,
			},
			true,
		},
		{
			"missing language",
			&Config{
				Schemas:  []*schema.Schema{validSchema},
				Compiler: validCompiler,
				OutDir:   "/tmp",
			},
			true,
		},
		{
			"unsupported language",
			&Config{
				Schemas:  []*schema.Schema{validSchema},
				Compiler: validCompiler,
				OutDir:   "/tmp",
				Language: "java",
			},
			true,
		},
		{
			"valid typescript",
			&Config{
				Schemas:  []*schema.Schema{validSchema},
				Compiler: validCompiler,
				OutDir:   "/tmp",
				Language: LanguageTypeScript,
			},
			false,
		},
		{
			"valid python",
			&Config{
				Schemas:  []*schema.Schema{validSchema},
				Compiler: validCompiler,
				OutDir:   "/tmp",
				Language: LanguagePython,
			},
			false,
		},
		{
			"valid go",
			&Config{
				Schemas:  []*schema.Schema{validSchema},
				Compiler: validCompiler,
				OutDir:   "/tmp",
				Language: LanguageGo,
			},
			false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := validateConfig(tt.cfg)
			if tt.wantErr {
				assert.Error(t, err)
			} else {
				assert.NoError(t, err)
			}
		})
	}
}

/*
 Run – happy paths
*/

func TestRun_SupportedLanguages(t *testing.T) {
	tests := []struct {
		name     string
		language Language
		expected string
	}{
		{"typescript", LanguageTypeScript, "types.ts"},
		{"python", LanguagePython, "types.py"},
		{"go", LanguageGo, "types.go"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			outDir := t.TempDir()

			cfg := &Config{
				Schemas:        []*schema.Schema{createTestSchema(t, "User")},
				Compiler:       createTestCompiler(t),
				OutDir:         outDir,
				Language:       tt.language,
				OutputStrategy: output.StrategyBundle,
			}

			require.NoError(t, Run(cfg))
			assert.FileExists(t, filepath.Join(outDir, tt.expected))
		})
	}
}

/*
 Run – multifile strategy
*/

func TestRun_MultiFileStrategy(t *testing.T) {
	outDir := t.TempDir()

	cfg := &Config{
		Schemas:        []*schema.Schema{createTestSchema(t, "User")},
		Compiler:       createTestCompiler(t),
		OutDir:         outDir,
		Language:       LanguageTypeScript,
		OutputStrategy: output.StrategyMultiFile,
	}

	require.NoError(t, Run(cfg))
	assert.FileExists(t, filepath.Join(outDir, "index.ts"))
}

/*
 Run – headers
*/

func TestRun_DisableHeaders(t *testing.T) {
	outDir := t.TempDir()

	cfg := &Config{
		Schemas:        []*schema.Schema{createTestSchema(t, "User")},
		Compiler:       createTestCompiler(t),
		OutDir:         outDir,
		Language:       LanguageTypeScript,
		OutputStrategy: output.StrategyBundle,
		DisableHeaders: true,
	}

	require.NoError(t, Run(cfg))

	data, err := os.ReadFile(filepath.Join(outDir, "types.ts"))
	require.NoError(t, err)

	assert.NotContains(t, string(data), "Code generated by")
}

/*
 Run – Go always extracts inline
*/

func TestRun_GoAlwaysExtractsInline(t *testing.T) {
	outDir := t.TempDir()

	cfg := &Config{
		Schemas:        []*schema.Schema{createTestSchema(t, "User")},
		Compiler:       createTestCompiler(t),
		OutDir:         outDir,
		Language:       LanguageGo,
		OutputStrategy: output.StrategyBundle,
		ExtractInline:  false, // ignored for Go
		Go: &GoConfig{
			PackageName: "models",
		},
	}

	require.NoError(t, Run(cfg))

	data, err := os.ReadFile(filepath.Join(outDir, "types.go"))
	require.NoError(t, err)

	assert.NotContains(t, string(data), "map[string]interface{}")
}

/*
 Run – invalid cases
*/

func TestRun_InvalidLanguage(t *testing.T) {
	outDir := t.TempDir()

	cfg := &Config{
		Schemas:        []*schema.Schema{createTestSchema(t, "User")},
		Compiler:       createTestCompiler(t),
		OutDir:         outDir,
		Language:       "rust",
		OutputStrategy: output.StrategyBundle,
	}

	err := Run(cfg)
	assert.Error(t, err)
	assert.Contains(t, err.Error(), "unsupported")
}

func TestRun_EmptySchemas(t *testing.T) {
	outDir := t.TempDir()

	cfg := &Config{
		Schemas:        []*schema.Schema{},
		Compiler:       createTestCompiler(t),
		OutDir:         outDir,
		Language:       LanguageTypeScript,
		OutputStrategy: output.StrategyBundle,
	}

	err := Run(cfg)
	assert.Error(t, err)
}
