// Code generated by schemagen. DO NOT EDIT.

export type LogLevel = "debug" | "info" | "warn" | "error";

/**
 * Application settings
 */
export interface Settings {
  debug?: boolean;
  logLevel?: LogLevel;
  maxConnections?: number;
}
