// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

export const CodeSchema = z.enum(["US", "CA", "UK", "FR", "DE", "JP"]);

export type Code = z.infer<typeof CodeSchema>;

/**
 * Country information
 */
export const CountrySchema = z.object({
  name: z.string(),
  code: CodeSchema,
}).meta({ description: "Country information" });

export type Country = z.infer<typeof CountrySchema>;

/**
 * Address with country reference
 */
export const AddressSchema = z.object({
  street: z.string(),
  city: z.string(),
  zipCode: z.string().optional(),
  country: CountrySchema.meta({ description: "Reference to Country" }),
}).meta({ description: "Address with country reference" });

export type Address = z.infer<typeof AddressSchema>;

/**
 * Office with address reference
 */
export const OfficeSchema = z.object({
  name: z.string(),
  address: AddressSchema.meta({ description: "Reference to Address (which references Country)" }),
  employees: z.int().gte(1).optional(),
}).meta({ description: "Office with address reference" });

export type Office = z.infer<typeof OfficeSchema>;

/**
 * Organization schema with chained internal references
 */
export const OrganizationSchema = z.object({
  id: z.uuid(),
  name: z.string(),
  headquarters: OfficeSchema.meta({ description: "Main office (references Office → Address → Country)" }),
  branches: z.array(OfficeSchema).optional().meta({ description: "Branch offices (reuses Office type multiple times)" }),
}).meta({ description: "Organization schema with chained internal references" });

export type Organization = z.infer<typeof OrganizationSchema>;
