# Code generated by schemagen. DO NOT EDIT.

from __future__ import annotations

from pydantic import BaseModel, Field

from .header import EventHeader
from .meta import EventMetadata
from .payloads.ping import PingPayload
from .payloads.pong import PongPayload
from .payloads.subscribe import SubscribePayload
from .payloads.unsubscribe import UnsubscribePayload


class Event(BaseModel):
    """Main event schema with external references"""

    header: EventHeader = Field(..., description="Event header (external ref without fragment)")
    meta: EventMetadata = Field(..., description="Event metadata (external ref without fragment)")
    payload: SubscribePayload | UnsubscribePayload | PingPayload | PongPayload = Field(..., description="Event payload (varies by event type)")
