# Code generated by schemagen. DO NOT EDIT.

from __future__ import annotations

from datetime import datetime
from enum import Enum
from uuid import UUID

from pydantic import BaseModel, Field, AnyUrl


class EventType(str, Enum):
    """Type of event"""

    SUBSCRIBE = "subscribe"
    UNSUBSCRIBE = "unsubscribe"
    PING = "ping"
    PONG = "pong"


class EventHeader(BaseModel):
    """Standard event header with metadata"""

    id: UUID = Field(..., description="Unique event identifier")
    type: EventType
    timestamp: datetime = Field(..., description="When the event occurred")
    source: AnyUrl = Field(..., description="Event source system")
