# Code generated by schemagen. DO NOT EDIT.

from __future__ import annotations

from uuid import UUID

from pydantic import BaseModel, Field


class EventMetadata(BaseModel):
    """Event metadata for tracing and correlation"""

    correlationId: UUID = Field(..., description="Correlation ID for tracking related events")
    userId: str | None = Field(None, description="User who triggered the event")
    sessionId: str | None = Field(None, description="Session identifier")
    ttl: int | None = Field(None, description="Time to live in seconds", ge=0)
