# Code generated by schemagen. DO NOT EDIT.

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import BaseModel, Field, EmailStr


class Commenter(BaseModel):
    """Nested inline commenter object (should be extracted)"""

    email: EmailStr
    name: str


class CommentsItem(BaseModel):
    """Inline comment object (should be extracted)"""

    commenter: Commenter = Field(..., description="Nested inline commenter object (should be extracted)")
    id: UUID
    text: str


class Role(str, Enum):
    ADMIN = "admin"
    EDITOR = "editor"
    CONTRIBUTOR = "contributor"


class Author(BaseModel):
    """Inline author object (should be extracted)"""

    email: EmailStr
    name: str
    role: Role | None = None


class Status(str, Enum):
    DRAFT = "draft"
    PUBLISHED = "published"
    ARCHIVED = "archived"


class BlogPost(BaseModel):
    """Blog post with deeply nested inline types for extraction testing"""

    id: UUID
    title: str
    content: str | None = None
    status: Status
    author: Author = Field(..., description="Inline author object (should be extracted)")
    tags: list[str] | None = None
    comments: list[CommentsItem] | None = Field(None, description="Array of inline comment objects")
