// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

import { SettingsSchema } from './settings';

/**
 * Application configuration (YAML format test)
 */
export const ConfigSchema = z.object({
  appName: z.string(),
  settings: SettingsSchema.optional(),
  version: z.string(),
}).meta({ description: "Application configuration (YAML format test)" });

export type Config = z.infer<typeof ConfigSchema>;
