// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

export const LogLevelSchema = z.enum(["debug", "info", "warn", "error"]);

export type LogLevel = z.infer<typeof LogLevelSchema>;

/**
 * Application settings
 */
export const SettingsSchema = z.object({
  debug: z.boolean().optional(),
  logLevel: LogLevelSchema.optional(),
  maxConnections: z.int().gte(1).optional(),
}).meta({ description: "Application settings" });

export type Settings = z.infer<typeof SettingsSchema>;
