// Code generated by schemagen. DO NOT EDIT.

/**
 * Inline author object (should be extracted)
 */
export interface Author {
  /**
   * @format email
   */
  email: string;
  name: string;
  role?: Role;
}

/**
 * Blog post with deeply nested inline types for extraction testing
 */
export interface BlogPost {
  /**
   * @format uuid
   */
  id: string;
  title: string;
  content?: string;
  status: Status;
  /** Inline author object (should be extracted) */
  author: Author;
  tags?: string[];
  /** Array of inline comment objects */
  comments?: CommentsItem[];
}

/**
 * Nested inline commenter object (should be extracted)
 */
export interface Commenter {
  /**
   * @format email
   */
  email: string;
  name: string;
}

/**
 * Inline comment object (should be extracted)
 */
export interface CommentsItem {
  /** Nested inline commenter object (should be extracted) */
  commenter: Commenter;
  /**
   * @format uuid
   */
  id: string;
  text: string;
}

export type Role = "admin" | "editor" | "contributor";

export type Status = "draft" | "published" | "archived";
