// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

import type { EventHeader } from './header';
import { EventHeaderSchema } from './header';
import type { EventMetadata } from './meta';
import { EventMetadataSchema } from './meta';
import type { PingPayload } from './payloads/ping';
import { PingPayloadSchema } from './payloads/ping';
import type { PongPayload } from './payloads/pong';
import { PongPayloadSchema } from './payloads/pong';
import type { SubscribePayload } from './payloads/subscribe';
import { SubscribePayloadSchema } from './payloads/subscribe';
import type { UnsubscribePayload } from './payloads/unsubscribe';
import { UnsubscribePayloadSchema } from './payloads/unsubscribe';

/**
 * Main event schema with external references
 */
export interface Event {
  /** Event header (external ref without fragment) */
  header: EventHeader;
  /** Event metadata (external ref without fragment) */
  meta: EventMetadata;
  /** Event payload (varies by event type) */
  payload: SubscribePayload | UnsubscribePayload | PingPayload | PongPayload;
}

export const EventSchema = z.object({
  header: EventHeaderSchema.meta({ description: "Event header (external ref without fragment)" }),
  meta: EventMetadataSchema.meta({ description: "Event metadata (external ref without fragment)" }),
  payload: z.union([SubscribePayloadSchema, UnsubscribePayloadSchema, PingPayloadSchema, PongPayloadSchema]).meta({ description: "Event payload (varies by event type)" }),
}).meta({ description: "Main event schema with external references" });
