// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

/**
 * Type of event
 */
export type EventType = "subscribe" | "unsubscribe" | "ping" | "pong";

export const EventTypeSchema = z.enum(["subscribe", "unsubscribe", "ping", "pong"]).meta({ description: "Type of event" });

/**
 * Standard event header with metadata
 */
export interface EventHeader {
  /**
   * Unique event identifier
   * @format uuid
   */
  id: string;
  type: EventType;
  /**
   * When the event occurred
   * @format date-time
   */
  timestamp: string;
  /**
   * Event source system
   * @format uri
   */
  source: string;
}

export const EventHeaderSchema = z.object({
  id: z.uuid().meta({ description: "Unique event identifier" }),
  type: EventTypeSchema,
  timestamp: z.iso.datetime().meta({ description: "When the event occurred" }),
  source: z.url().meta({ description: "Event source system" }),
}).meta({ description: "Standard event header with metadata" });
