// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

/**
 * Event metadata for tracing and correlation
 */
export interface EventMetadata {
  /**
   * Correlation ID for tracking related events
   * @format uuid
   */
  correlationId: string;
  /** User who triggered the event */
  userId?: string;
  /** Session identifier */
  sessionId?: string;
  /** Time to live in seconds */
  ttl?: number;
}

export const EventMetadataSchema = z.object({
  correlationId: z.uuid().meta({ description: "Correlation ID for tracking related events" }),
  userId: z.string().optional().meta({ description: "User who triggered the event" }),
  sessionId: z.string().optional().meta({ description: "Session identifier" }),
  ttl: z.int().gte(0).optional().meta({ description: "Time to live in seconds" }),
}).meta({ description: "Event metadata for tracing and correlation" });
