// Code generated by schemagen. DO NOT EDIT.

package models

import (
	"github.com/go-playground/validator/v10"
	"time"
)

type Address struct {
	Name string `json:"name" validate:"required"`
	Street string `json:"street" validate:"required"`
	City string `json:"city" validate:"required"`
	State *string `json:"state,omitempty"`
	ZipCode *string `json:"zipCode,omitempty"`
	Country string `json:"country" validate:"required"`
}

type Currency string

const (
	CurrencyUSD Currency = "USD"
	CurrencyEUR Currency = "EUR"
	CurrencyGBP Currency = "GBP"
	CurrencyJPY Currency = "JPY"
)

// EcommerceOrder Production-like ecommerce order schema
type EcommerceOrder struct {
	OrderId string `json:"orderId" validate:"required"`
	CustomerId string `json:"customerId" validate:"required"`
	OrderDate time.Time `json:"orderDate" validate:"required"`
	Status Status `json:"status" validate:"required"`
	Items []LineItem `json:"items" validate:"required,min=1"`
	ShippingAddress Address `json:"shippingAddress" validate:"required"`
	BillingAddress *Address `json:"billingAddress,omitempty"`
	Subtotal *Money `json:"subtotal,omitempty"`
	Tax *Money `json:"tax,omitempty"`
	Shipping *Money `json:"shipping,omitempty"`
	Total Money `json:"total" validate:"required"`
}

type LineItem struct {
	ProductId string `json:"productId" validate:"required"`
	ProductName string `json:"productName" validate:"required"`
	Quantity int `json:"quantity" validate:"required,gte=1"`
	UnitPrice Money `json:"unitPrice" validate:"required"`
	TotalPrice Money `json:"totalPrice" validate:"required"`
}

type Money struct {
	Amount float64 `json:"amount" validate:"required,gte=0"`
	Currency Currency `json:"currency" validate:"required"`
}

type Status string

const (
	StatusPENDING Status = "pending"
	StatusPROCESSING Status = "processing"
	StatusSHIPPED Status = "shipped"
	StatusDELIVERED Status = "delivered"
	StatusCANCELLED Status = "cancelled"
)