// Code generated by schemagen. DO NOT EDIT.

package models

import (
	_ "github.com/go-playground/validator/v10"
	"github.com/mirpo/schemagen/testdata/expected/header"
	"github.com/mirpo/schemagen/testdata/expected/meta"
	"github.com/mirpo/schemagen/testdata/expected/payloads/ping"
	"github.com/mirpo/schemagen/testdata/expected/payloads/pong"
	"github.com/mirpo/schemagen/testdata/expected/payloads/subscribe"
	"github.com/mirpo/schemagen/testdata/expected/payloads/unsubscribe"
)

// Event Main event schema with external references
type Event struct {
	// Event header (external ref without fragment)
	Header EventHeader `json:"header" validate:"required"`
	// Event metadata (external ref without fragment)
	Meta EventMetadata `json:"meta" validate:"required"`
	// Event payload (varies by event type)
	// Can be one of: SubscribePayload, UnsubscribePayload, PingPayload, PongPayload
	Payload any `json:"payload" validate:"required"`
}