// Code generated by schemagen. DO NOT EDIT.

package models

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/uuid"
	"time"
)

// EventHeader Standard event header with metadata
type EventHeader struct {
	// Unique event identifier
	Id uuid.UUID `json:"id" validate:"required,uuid"`
	Type EventType `json:"type" validate:"required"`
	// When the event occurred
	Timestamp time.Time `json:"timestamp" validate:"required"`
	// Event source system
	Source string `json:"source" validate:"required,url"`
}

// EventType Type of event
type EventType string

const (
	EventTypeSUBSCRIBE EventType = "subscribe"
	EventTypeUNSUBSCRIBE EventType = "unsubscribe"
	EventTypePING EventType = "ping"
	EventTypePONG EventType = "pong"
)