// Code generated by schemagen. DO NOT EDIT.

package models

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/uuid"
)

// EventMetadata Event metadata for tracing and correlation
type EventMetadata struct {
	// Correlation ID for tracking related events
	CorrelationId uuid.UUID `json:"correlationId" validate:"required,uuid"`
	// User who triggered the event
	UserId *string `json:"userId,omitempty"`
	// Session identifier
	SessionId *string `json:"sessionId,omitempty"`
	// Time to live in seconds
	Ttl *int `json:"ttl,omitempty" validate:"gte=0"`
}