// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

export const CurrencySchema = z.enum(["USD", "EUR", "GBP", "JPY"]);

export type Currency = z.infer<typeof CurrencySchema>;

export const MoneySchema = z.object({
  amount: z.number().gte(0),
  currency: CurrencySchema,
});

export type Money = z.infer<typeof MoneySchema>;

export const AddressSchema = z.object({
  name: z.string(),
  street: z.string(),
  city: z.string(),
  state: z.string().optional(),
  zipCode: z.string().optional(),
  country: z.string(),
});

export type Address = z.infer<typeof AddressSchema>;

export const LineItemSchema = z.object({
  productId: z.string(),
  productName: z.string(),
  quantity: z.int().gte(1),
  unitPrice: MoneySchema,
  totalPrice: MoneySchema,
});

export type LineItem = z.infer<typeof LineItemSchema>;

export const StatusSchema = z.enum(["pending", "processing", "shipped", "delivered", "cancelled"]);

export type Status = z.infer<typeof StatusSchema>;

/**
 * Production-like ecommerce order schema
 */
export const EcommerceOrderSchema = z.object({
  orderId: z.string(),
  customerId: z.string(),
  orderDate: z.iso.datetime(),
  status: StatusSchema,
  items: z.array(LineItemSchema).min(1),
  shippingAddress: AddressSchema,
  billingAddress: AddressSchema.optional(),
  subtotal: MoneySchema.optional(),
  tax: MoneySchema.optional(),
  shipping: MoneySchema.optional(),
  total: MoneySchema,
}).meta({ description: "Production-like ecommerce order schema" });

export type EcommerceOrder = z.infer<typeof EcommerceOrderSchema>;
