// Code generated by schemagen. DO NOT EDIT.

package models

import (
	_ "github.com/go-playground/validator/v10"
)

// CyclicRef Type with cyclic reference to itself
type CyclicRef struct {
	// Unique identifier
	Id string `json:"id" validate:"required"`
	Name *string `json:"name,omitempty"`
	// Reference to parent node (cyclic)
	Parent *CyclicRef `json:"parent,omitempty"`
	// Child nodes (cyclic)
	Children *[]CyclicRef `json:"children,omitempty"`
}