// Code generated by schemagen. DO NOT EDIT.

package models

// DescriptionQuotes This has "double quotes" and '''triple single''' and """triple double""" quotes
type DescriptionQuotes struct {
	// Field with "quotes" and \backslash in description
	Field *string `json:"field,omitempty"`
}