// Code generated by schemagen. DO NOT EDIT.

package models

// EnumComplex Enum with complex values (objects/arrays) - all preserved in output
type EnumComplex any

var EnumComplexValues = []EnumComplex{
	"simple",
	map[string]any{"complex": true},
	42,
	[]any{"array", "value"},
	map[string]any{"alpha": 2, "beta": 4, "mango": 3, "zebra": 1},
}