// Code generated by schemagen. DO NOT EDIT.

package models

import (
	_ "github.com/go-playground/validator/v10"
)

// SpecialProps Object with special property names requiring aliases
type SpecialProps struct {
	// Property with kebab-case name
	KebabCase string `json:"kebab-case" validate:"required"`
	// Property with spaces
	WithSpaces *string `json:"with spaces,omitempty"`
	// Property starting with number
	F123Numeric *int `json:"123numeric,omitempty"`
	// Property starting with dollar
	FDollar *bool `json:"$dollar,omitempty"`
	// Python reserved keyword
	Class *string `json:"class,omitempty"`
	// Python reserved keyword
	From *string `json:"from,omitempty"`
}