// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

/**
 * Message priority level
 */
export const PrioritySchema = z.enum(["low", "normal", "high", "critical"]).meta({ description: "Message priority level" });

export type Priority = z.infer<typeof PrioritySchema>;

/**
 * Message in a queue or topic
 */
export const MessageSchema = z.object({
  id: z.uuid().meta({ description: "Unique message identifier" }),
  topic: z.string().meta({ description: "Message topic or queue name" }),
  payload: z.record(z.string(), z.unknown()).meta({ description: "Message payload (any structure)" }),
  timestamp: z.iso.datetime().meta({ description: "When the message was created" }),
  ttl: z.int().gte(0).optional().meta({ description: "Time to live in seconds" }),
  retryCount: z.int().gte(0).lte(10).optional().meta({ description: "Number of delivery attempts" }),
  priority: PrioritySchema.optional().meta({ description: "Message priority level" }),
}).meta({ description: "Message in a queue or topic" });

export type Message = z.infer<typeof MessageSchema>;

/**
 * Delivery guarantee level
 */
export const DeliveryModeSchema = z.enum(["at-most-once", "at-least-once", "exactly-once"]).meta({ description: "Delivery guarantee level" });

export type DeliveryMode = z.infer<typeof DeliveryModeSchema>;

/**
 * Subscription to a topic
 */
export const SubscriptionSchema = z.object({
  id: z.uuid(),
  topic: z.string().meta({ description: "Topic pattern to subscribe to" }),
  filters: z.record(z.string(), z.string()).optional().meta({ description: "Message filtering rules" }),
  deliveryMode: DeliveryModeSchema.meta({ description: "Delivery guarantee level" }),
  endpoint: z.url().optional().meta({ description: "Webhook URL for message delivery" }),
}).meta({ description: "Subscription to a topic" });

export type Subscription = z.infer<typeof SubscriptionSchema>;

/**
 * API error details
 */
export const ErrorSchema = z.object({
  code: z.string().meta({ description: "Error code" }),
  message: z.string().meta({ description: "Human-readable error message" }),
  field: z.string().optional().meta({ description: "Field that caused the error" }),
  details: z.record(z.string(), z.unknown()).optional().meta({ description: "Additional error context" }),
}).meta({ description: "API error details" });

export type Error = z.infer<typeof ErrorSchema>;

/**
 * Pagination information
 */
export const PaginationSchema = z.object({
  page: z.int().gte(1).meta({ description: "Current page number" }),
  pageSize: z.int().gte(1).lte(100).meta({ description: "Items per page" }),
  totalPages: z.int().gte(0).meta({ description: "Total number of pages" }),
  totalItems: z.int().gte(0).meta({ description: "Total number of items" }),
  hasNext: z.boolean().optional().meta({ description: "Whether there is a next page" }),
  hasPrevious: z.boolean().optional().meta({ description: "Whether there is a previous page" }),
}).meta({ description: "Pagination information" });

export type Pagination = z.infer<typeof PaginationSchema>;

/**
 * Response metadata (inline object, not a $def)
 */
export const MetadataSchema = z.object({
  region: z.string().optional().meta({ description: "Server region that handled the request" }),
  requestId: z.uuid().meta({ description: "Unique request identifier for tracing" }),
  timestamp: z.iso.datetime().meta({ description: "When the response was generated" }),
  version: z.string().meta({ description: "API version" }),
}).meta({ description: "Response metadata (inline object, not a $def)" });

export type Metadata = z.infer<typeof MetadataSchema>;

/**
 * Nested inline object
 */
export const ThroughputSchema = z.object({
  bytesPerSecond: z.number().gte(0).optional(),
  messagesPerSecond: z.number().gte(0).optional(),
}).meta({ description: "Nested inline object" });

export type Throughput = z.infer<typeof ThroughputSchema>;

/**
 * Queue statistics (inline object)
 */
export const StatsSchema = z.object({
  activeSubscriptions: z.int().gte(0).optional(),
  pendingMessages: z.int().gte(0).optional(),
  throughput: ThroughputSchema.optional().meta({ description: "Nested inline object" }),
  totalMessages: z.int().gte(0).optional(),
}).meta({ description: "Queue statistics (inline object)" });

export type Stats = z.infer<typeof StatsSchema>;

/**
 * Real-world messaging API with pagination, errors, and message queue concepts
 */
export const MessagingAPISchema = z.object({
  messages: z.array(MessageSchema).optional().meta({ description: "List of messages" }),
  subscriptions: z.array(SubscriptionSchema).optional().meta({ description: "Active subscriptions" }),
  pagination: PaginationSchema.optional(),
  errors: z.array(ErrorSchema).optional().meta({ description: "Any errors encountered" }),
  metadata: MetadataSchema.meta({ description: "Response metadata (inline object, not a $def)" }),
  stats: StatsSchema.optional().meta({ description: "Queue statistics (inline object)" }),
}).meta({ description: "Real-world messaging API with pagination, errors, and message queue concepts" });

export type MessagingAPI = z.infer<typeof MessagingAPISchema>;
