// Code generated by schemagen. DO NOT EDIT.

/**
 * Message priority level
 */
export type Priority = "low" | "normal" | "high" | "critical";

/**
 * Message in a queue or topic
 */
export interface Message {
  /**
   * Unique message identifier
   * @format uuid
   */
  id: string;
  /** Message topic or queue name */
  topic: string;
  /** Message payload (any structure) */
  payload: Record<string, any>;
  /**
   * When the message was created
   * @format date-time
   */
  timestamp: string;
  /** Time to live in seconds */
  ttl?: number;
  /** Number of delivery attempts */
  retryCount?: number;
  /** Message priority level */
  priority?: Priority;
}

/**
 * Delivery guarantee level
 */
export type DeliveryMode = "at-most-once" | "at-least-once" | "exactly-once";

/**
 * Subscription to a topic
 */
export interface Subscription {
  /**
   * @format uuid
   */
  id: string;
  /** Topic pattern to subscribe to */
  topic: string;
  /** Message filtering rules */
  filters?: Record<string, string>;
  /** Delivery guarantee level */
  deliveryMode: DeliveryMode;
  /**
   * Webhook URL for message delivery
   * @format uri
   */
  endpoint?: string;
}

/**
 * API error details
 */
export interface Error {
  /** Error code */
  code: string;
  /** Human-readable error message */
  message: string;
  /** Field that caused the error */
  field?: string;
  /** Additional error context */
  details?: Record<string, any>;
}

/**
 * Pagination information
 */
export interface Pagination {
  /** Current page number */
  page: number;
  /** Items per page */
  pageSize: number;
  /** Total number of pages */
  totalPages: number;
  /** Total number of items */
  totalItems: number;
  /** Whether there is a next page */
  hasNext?: boolean;
  /** Whether there is a previous page */
  hasPrevious?: boolean;
}

/**
 * Response metadata (inline object, not a $def)
 */
export interface Metadata {
  /** Server region that handled the request */
  region?: string;
  /**
   * Unique request identifier for tracing
   * @format uuid
   */
  requestId: string;
  /**
   * When the response was generated
   * @format date-time
   */
  timestamp: string;
  /** API version */
  version: string;
}

/**
 * Nested inline object
 */
export interface Throughput {
  bytesPerSecond?: number;
  messagesPerSecond?: number;
}

/**
 * Queue statistics (inline object)
 */
export interface Stats {
  activeSubscriptions?: number;
  pendingMessages?: number;
  /** Nested inline object */
  throughput?: Throughput;
  totalMessages?: number;
}

/**
 * Real-world messaging API with pagination, errors, and message queue concepts
 */
export interface MessagingAPI {
  /** List of messages */
  messages?: Message[];
  /** Active subscriptions */
  subscriptions?: Subscription[];
  pagination?: Pagination;
  /** Any errors encountered */
  errors?: Error[];
  /** Response metadata (inline object, not a $def) */
  metadata: Metadata;
  /** Queue statistics (inline object) */
  stats?: Stats;
}
