// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

export const EntitySchema = z.object({
  id: z.uuid(),
});

export type Entity = z.infer<typeof EntitySchema>;

export const AuditableSchema = z.object({
  createdBy: z.string(),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime().optional(),
});

export type Auditable = z.infer<typeof AuditableSchema>;

/**
 * Document with multiple mixins - tests allOf with refs, inline objects, and field deduplication
 */
export const DocumentSchema = EntitySchema.merge(AuditableSchema).extend({
  title: z.string().meta({ description: "First title definition" }),
  content: z.string(),
  author: z.string().optional(),
  tags: z.array(z.string()).optional(),
}).meta({ description: "Document with multiple mixins - tests allOf with refs, inline objects, and field deduplication" });

export type Document = z.infer<typeof DocumentSchema>;
