// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

export const IdObjectSchema = z.object({
  id: z.uuid(),
});

export type IdObject = z.infer<typeof IdObjectSchema>;

export const TimestampedSchema = z.object({
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime().optional(),
});

export type Timestamped = z.infer<typeof TimestampedSchema>;

export const PersonSchema = z.object({
  email: z.email().optional(),
  name: z.string().optional(),
});

export type Person = z.infer<typeof PersonSchema>;

export const NodeSchema = z.object({
  value: z.string().optional(),
  get next() { return NodeSchema.optional() },
});

export type Node = z.infer<typeof NodeSchema>;

export const StatusSchema = z.union([z.literal("active"), z.literal("paused"), z.object({ complex: z.literal(true) }).strict()]);

export type Status = z.infer<typeof StatusSchema>;

export const PayloadSchema = z.object({
  data: z.string(),
  type: z.enum(["A"]),
});

export type Payload = z.infer<typeof PayloadSchema>;

export const Payload1Schema = z.object({
  data: z.number(),
  type: z.enum(["B"]),
});

export type Payload1 = z.infer<typeof Payload1Schema>;

/**
 * One schema to test everything
 */
export const MegaTestSchema = IdObjectSchema.merge(TimestampedSchema).extend({
  tags: z.array(z.string()).min(1),
  owner: PersonSchema.optional(),
  status: StatusSchema,
  meta: z.record(z.string(), z.string()).optional(),
  payload: z.union([PayloadSchema, Payload1Schema]).optional(),
  node: NodeSchema.optional(),
}).meta({ description: "One schema to test everything" });

export type MegaTest = z.infer<typeof MegaTestSchema>;
