// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

import type { Settings } from './settings';
import { SettingsSchema } from './settings';

/**
 * Application configuration (YAML format test)
 */
export interface Config {
  appName: string;
  settings?: Settings;
  version: string;
}

export const ConfigSchema = z.object({
  appName: z.string(),
  settings: SettingsSchema.optional(),
  version: z.string(),
}).meta({ description: "Application configuration (YAML format test)" });
