// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

export type LogLevel = "debug" | "info" | "warn" | "error";

export const LogLevelSchema = z.enum(["debug", "info", "warn", "error"]);

/**
 * Application settings
 */
export interface Settings {
  debug?: boolean;
  logLevel?: LogLevel;
  maxConnections?: number;
}

export const SettingsSchema = z.object({
  debug: z.boolean().optional(),
  logLevel: LogLevelSchema.optional(),
  maxConnections: z.int().gte(1).optional(),
}).meta({ description: "Application settings" });
