// Code generated by schemagen. DO NOT EDIT.

package models

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/uuid"
	"time"
)

// AdditionalProps Additional properties patterns
type AdditionalProps struct {
	// Any additional properties allowed
	Flexible *Flexible `json:"flexible,omitempty"`
	// No additional properties allowed
	Strict *Strict `json:"strict,omitempty"`
	// Additional properties must be numbers
	TypedMap *TypedMap `json:"typedMap,omitempty"`
}

type Arrays struct {
	// Array with size constraints
	MinMaxArray *[]string `json:"minMaxArray,omitempty" validate:"min=1,max=10"`
}

// Arrays2 Array types
type Arrays2 struct {
	// Array of numbers
	NumberArray *[]float64 `json:"numberArray,omitempty"`
	// Array of objects
	ObjectArray *[]ObjectArrayItem `json:"objectArray,omitempty"`
	// Array of strings
	StringArray *[]string `json:"stringArray,omitempty"`
}

// Constraints Validation constraints
type Constraints struct {
	Arrays *Arrays `json:"arrays,omitempty"`
	Numbers *Numbers `json:"numbers,omitempty"`
	Strings *Strings `json:"strings,omitempty"`
}

// EdgeCases Edge cases: reserved keywords and special characters
type EdgeCases struct {
	// Empty object with no properties
	EmptyConfig *map[string]interface{} `json:"emptyConfig,omitempty"`
	// Reserved keywords in TypeScript and Python
	ReservedKeywords *ReservedKeywords `json:"reservedKeywords,omitempty"`
	// Special characters in property names
	SpecialChars *SpecialChars `json:"specialChars,omitempty"`
}

// Enums Enumeration types
type Enums struct {
	// Mixed type enumeration
	MixedEnum *MixedEnum `json:"mixedEnum,omitempty"`
	// Number enumeration
	NumberEnum *NumberEnum `json:"numberEnum,omitempty"`
	// String enumeration
	StringEnum *StringEnum `json:"stringEnum,omitempty"`
}

// Flexible Any additional properties allowed
type Flexible struct {
	Enabled *bool `json:"enabled,omitempty"`
	Version string `json:"version" validate:"required"`
}

// Formats String formats for validation
type Formats struct {
	// Date only (YYYY-MM-DD)
	Date *time.Time `json:"date,omitempty"`
	// Full timestamp with timezone
	DateTime *time.Time `json:"dateTime,omitempty"`
	// User email address
	Email *string `json:"email,omitempty" validate:"email"`
	// IPv4 address
	Ipv4 *string `json:"ipv4,omitempty"`
	// IPv6 address
	Ipv6 *string `json:"ipv6,omitempty"`
	// Time only (HH:MM:SS)
	Time *string `json:"time,omitempty"`
	// Resource URL
	Uri *string `json:"uri,omitempty" validate:"url"`
	// Unique identifier
	Uuid *uuid.UUID `json:"uuid,omitempty" validate:"uuid"`
}

// Foundation Comprehensive test of all basic types, formats, constraints, and edge cases
type Foundation struct {
	// All primitive types
	Primitives Primitives `json:"primitives" validate:"required"`
	// String formats for validation
	Formats *Formats `json:"formats,omitempty"`
	// Validation constraints
	Constraints *Constraints `json:"constraints,omitempty"`
	// Enumeration types
	Enums *Enums `json:"enums,omitempty"`
	// Array types
	Arrays *Arrays2 `json:"arrays,omitempty"`
	// Nested object structure
	Nested *Nested `json:"nested,omitempty"`
	// Required vs optional fields
	Nullable *Nullable `json:"nullable,omitempty"`
	// Additional properties patterns
	AdditionalProps *AdditionalProps `json:"additionalProps,omitempty"`
	// Edge cases: reserved keywords and special characters
	EdgeCases *EdgeCases `json:"edgeCases,omitempty"`
}

type Level1 struct {
	Level2 *Level2 `json:"level2,omitempty"`
}

type Level2 struct {
	// Three levels deep
	Level3 *string `json:"level3,omitempty"`
}

// MixedEnum Mixed type enumeration
type MixedEnum any

var MixedEnumValues = []MixedEnum{
	"string",
	42,
	true,
	nil,
}

// Nested Nested object structure
type Nested struct {
	Level1 *Level1 `json:"level1,omitempty"`
}

// Nullable Required vs optional fields
type Nullable struct {
	OptionalArray *[]string `json:"optionalArray,omitempty"`
	OptionalNumber *float64 `json:"optionalNumber,omitempty"`
	OptionalObject *OptionalObject `json:"optionalObject,omitempty"`
	// This field is optional
	OptionalString *string `json:"optionalString,omitempty"`
	// This field is required
	RequiredString string `json:"requiredString" validate:"required"`
}

// NumberEnum Number enumeration
type NumberEnum int

const (
	NumberEnum1 NumberEnum = 1
	NumberEnum2 NumberEnum = 2
	NumberEnum3 NumberEnum = 3
)

type Numbers struct {
	// Number with exclusive bounds
	ExclusiveRange *float64 `json:"exclusiveRange,omitempty"`
	// Integer with constraints
	MinMaxInteger *int `json:"minMaxInteger,omitempty" validate:"gte=1,lte=999"`
	// Number with inclusive bounds
	MinMaxNumber *float64 `json:"minMaxNumber,omitempty" validate:"gte=0,lte=100"`
}

type ObjectArrayItem struct {
	Id *string `json:"id,omitempty"`
	Value *float64 `json:"value,omitempty"`
}

type OptionalObject struct {
	Field *string `json:"field,omitempty"`
}

// Primitives All primitive types
type Primitives struct {
	BooleanVal bool `json:"booleanVal" validate:"required"`
	IntegerVal int `json:"integerVal" validate:"required"`
	NumberVal float64 `json:"numberVal" validate:"required"`
	StringVal string `json:"stringVal" validate:"required"`
}

// ReservedKeywords Reserved keywords in TypeScript and Python
type ReservedKeywords struct {
	As *string `json:"as,omitempty"`
	Async *string `json:"async,omitempty"`
	Await *string `json:"await,omitempty"`
	Class *string `json:"class,omitempty"`
	Def *string `json:"def,omitempty"`
	Export *string `json:"export,omitempty"`
	From *string `json:"from,omitempty"`
	Import *string `json:"import,omitempty"`
	Interface *string `json:"interface,omitempty"`
	Lambda *string `json:"lambda,omitempty"`
	Return *string `json:"return,omitempty"`
	Type *string `json:"type,omitempty"`
	Yield *string `json:"yield,omitempty"`
}

// SpecialChars Special characters in property names
type SpecialChars struct {
	FDollar *string `json:"$dollar,omitempty"`
	F123Numeric *string `json:"123numeric,omitempty"`
	FSpecial *string `json:"@special,omitempty"`
	PascalCase *string `json:"PascalCase,omitempty"`
	CamelCase *string `json:"camelCase,omitempty"`
	KebabCase *string `json:"kebab-case,omitempty"`
	SnakeCase *string `json:"snake_case,omitempty"`
	WithSpaces *string `json:"with spaces,omitempty"`
	WithDots *string `json:"with.dots,omitempty"`
}

// Strict No additional properties allowed
type Strict struct {
	Id string `json:"id" validate:"required"`
	Name *string `json:"name,omitempty"`
}

// StringEnum String enumeration
type StringEnum string

const (
	StringEnumOPTION1 StringEnum = "option1"
	StringEnumOPTION2 StringEnum = "option2"
	StringEnumOPTION3 StringEnum = "option3"
)

type Strings struct {
	// String with length constraints
	MinMaxString *string `json:"minMaxString,omitempty" validate:"min=5,max=50"`
	// String matching regex pattern
	PatternString *string `json:"patternString,omitempty"`
}

// TypedMap Additional properties must be numbers
type TypedMap struct {
	Source *string `json:"source,omitempty"`
	Timestamp string `json:"timestamp" validate:"required"`
}