// Code generated by schemagen. DO NOT EDIT.

/**
 * Event metadata for tracing and correlation
 */
export interface EventMetadata {
  /**
   * Correlation ID for tracking related events
   * @format uuid
   */
  correlationId: string;
  /** User who triggered the event */
  userId?: string;
  /** Session identifier */
  sessionId?: string;
  /** Time to live in seconds */
  ttl?: number;
}
