// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

import { EventHeaderSchema } from './header';
import { EventMetadataSchema } from './meta';
import { PingPayloadSchema } from './payloads/ping';
import { PongPayloadSchema } from './payloads/pong';
import { SubscribePayloadSchema } from './payloads/subscribe';
import { UnsubscribePayloadSchema } from './payloads/unsubscribe';

/**
 * Main event schema with external references
 */
export const EventSchema = z.object({
  header: EventHeaderSchema.meta({ description: "Event header (external ref without fragment)" }),
  meta: EventMetadataSchema.meta({ description: "Event metadata (external ref without fragment)" }),
  payload: z.union([SubscribePayloadSchema, UnsubscribePayloadSchema, PingPayloadSchema, PongPayloadSchema]).meta({ description: "Event payload (varies by event type)" }),
}).meta({ description: "Main event schema with external references" });

export type Event = z.infer<typeof EventSchema>;
