// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

/**
 * Type of event
 */
export const EventTypeSchema = z.enum(["subscribe", "unsubscribe", "ping", "pong"]).meta({ description: "Type of event" });

export type EventType = z.infer<typeof EventTypeSchema>;

/**
 * Standard event header with metadata
 */
export const EventHeaderSchema = z.object({
  id: z.uuid().meta({ description: "Unique event identifier" }),
  type: EventTypeSchema,
  timestamp: z.iso.datetime().meta({ description: "When the event occurred" }),
  source: z.url().meta({ description: "Event source system" }),
}).meta({ description: "Standard event header with metadata" });

export type EventHeader = z.infer<typeof EventHeaderSchema>;
