// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

/**
 * Event metadata for tracing and correlation
 */
export const EventMetadataSchema = z.object({
  correlationId: z.uuid().meta({ description: "Correlation ID for tracking related events" }),
  userId: z.string().optional().meta({ description: "User who triggered the event" }),
  sessionId: z.string().optional().meta({ description: "Session identifier" }),
  ttl: z.int().gte(0).optional().meta({ description: "Time to live in seconds" }),
}).meta({ description: "Event metadata for tracing and correlation" });

export type EventMetadata = z.infer<typeof EventMetadataSchema>;
