# Code generated by schemagen. DO NOT EDIT.

from __future__ import annotations

from datetime import datetime
from enum import Enum, IntEnum
from uuid import UUID

from typing import Any, Literal
from pydantic import BaseModel, Field, EmailStr, AnyUrl


class Primitives(BaseModel):
    """All primitive types"""

    booleanVal: bool
    integerVal: int
    numberVal: float
    stringVal: str


class Formats(BaseModel):
    """String formats for validation"""

    date: datetime | None = Field(None, description="Date only (YYYY-MM-DD)")
    dateTime: datetime | None = Field(None, description="Full timestamp with timezone")
    email: EmailStr | None = Field(None, description="User email address")
    ipv4: str | None = Field(None, description="IPv4 address")
    ipv6: str | None = Field(None, description="IPv6 address")
    time: str | None = Field(None, description="Time only (HH:MM:SS)")
    uri: AnyUrl | None = Field(None, description="Resource URL")
    uuid: UUID | None = Field(None, description="Unique identifier")


class Arrays(BaseModel):
    minMaxArray: list[str] | None = Field(None, description="Array with size constraints", min_length=1, max_length=10)


class Numbers(BaseModel):
    exclusiveRange: float | None = Field(None, description="Number with exclusive bounds", gt=0, lt=100)
    minMaxInteger: int | None = Field(None, description="Integer with constraints", ge=1, le=999)
    minMaxNumber: float | None = Field(None, description="Number with inclusive bounds", ge=0, le=100)


class Strings(BaseModel):
    minMaxString: str | None = Field(None, description="String with length constraints", min_length=5, max_length=50)
    patternString: str | None = Field(None, description="String matching regex pattern", pattern="^[A-Z][a-z]+$")


class Constraints(BaseModel):
    """Validation constraints"""

    arrays: Arrays | None = None
    numbers: Numbers | None = None
    strings: Strings | None = None


# Mixed type enumeration
MixedEnum = Literal["string", 42, True, None]


class NumberEnum(IntEnum):
    """Number enumeration"""

    N_1 = 1
    N_2 = 2
    N_3 = 3


class StringEnum(str, Enum):
    """String enumeration"""

    OPTION1 = "option1"
    OPTION2 = "option2"
    OPTION3 = "option3"


class Enums(BaseModel):
    """Enumeration types"""

    mixedEnum: MixedEnum | None = Field(None, description="Mixed type enumeration")
    numberEnum: NumberEnum | None = Field(None, description="Number enumeration")
    stringEnum: StringEnum | None = Field(None, description="String enumeration")


class ObjectArrayItem(BaseModel):
    id: str | None = None
    value: float | None = None


class Arrays2(BaseModel):
    """Array types"""

    numberArray: list[float] | None = Field(None, description="Array of numbers")
    objectArray: list[ObjectArrayItem] | None = Field(None, description="Array of objects")
    stringArray: list[str] | None = Field(None, description="Array of strings")


class Level2(BaseModel):
    level3: str | None = Field(None, description="Three levels deep")


class Level1(BaseModel):
    level2: Level2 | None = None


class Nested(BaseModel):
    """Nested object structure"""

    level1: Level1 | None = None


class OptionalObject(BaseModel):
    field: str | None = None


class Nullable(BaseModel):
    """Required vs optional fields"""

    optionalArray: list[str] | None = None
    optionalNumber: float | None = None
    optionalObject: OptionalObject | None = None
    optionalString: str | None = Field(None, description="This field is optional")
    requiredString: str = Field(..., description="This field is required")


class Flexible(BaseModel):
    """Any additional properties allowed"""

    enabled: bool | None = None
    version: str


class Strict(BaseModel):
    """No additional properties allowed"""

    id: str
    name: str | None = None


class TypedMap(BaseModel):
    """Additional properties must be numbers"""

    source: str | None = None
    timestamp: str


class AdditionalProps(BaseModel):
    """Additional properties patterns"""

    flexible: Flexible | None = Field(None, description="Any additional properties allowed")
    strict: Strict | None = Field(None, description="No additional properties allowed")
    typedMap: TypedMap | None = Field(None, description="Additional properties must be numbers")


class ReservedKeywords(BaseModel):
    """Reserved keywords in TypeScript and Python"""

    as_: str | None = Field(None, alias="as")
    async_: str | None = Field(None, alias="async")
    await_: str | None = Field(None, alias="await")
    class_: str | None = Field(None, alias="class")
    def_: str | None = Field(None, alias="def")
    export: str | None = None
    from_: str | None = Field(None, alias="from")
    import_: str | None = Field(None, alias="import")
    interface: str | None = None
    lambda_: str | None = Field(None, alias="lambda")
    return_: str | None = Field(None, alias="return")
    type: str | None = None
    yield_: str | None = Field(None, alias="yield")


class SpecialChars(BaseModel):
    """Special characters in property names"""

    field__dollar: str | None = Field(None, alias="$dollar")
    field_123numeric: str | None = Field(None, alias="123numeric")
    field__special: str | None = Field(None, alias="@special")
    PascalCase: str | None = None
    camelCase: str | None = None
    kebab_case: str | None = Field(None, alias="kebab-case")
    snake_case: str | None = None
    with_spaces: str | None = Field(None, alias="with spaces")
    with_dots: str | None = Field(None, alias="with.dots")


class EdgeCases(BaseModel):
    """Edge cases: reserved keywords and special characters"""

    emptyConfig: dict[str, Any] | None = Field(None, description="Empty object with no properties")
    reservedKeywords: ReservedKeywords | None = Field(None, description="Reserved keywords in TypeScript and Python")
    specialChars: SpecialChars | None = Field(None, description="Special characters in property names")


class Foundation(BaseModel):
    """Comprehensive test of all basic types, formats, constraints, and edge cases"""

    primitives: Primitives = Field(..., description="All primitive types")
    formats: Formats | None = Field(None, description="String formats for validation")
    constraints: Constraints | None = Field(None, description="Validation constraints")
    enums: Enums | None = Field(None, description="Enumeration types")
    arrays: Arrays2 | None = Field(None, description="Array types")
    nested: Nested | None = Field(None, description="Nested object structure")
    nullable: Nullable | None = Field(None, description="Required vs optional fields")
    additionalProps: AdditionalProps | None = Field(None, description="Additional properties patterns")
    edgeCases: EdgeCases | None = Field(None, description="Edge cases: reserved keywords and special characters")
