# Code generated by schemagen. DO NOT EDIT.

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import BaseModel, Field


class Code(str, Enum):
    US = "US"
    CA = "CA"
    UK = "UK"
    FR = "FR"
    DE = "DE"
    JP = "JP"


class Country(BaseModel):
    """Country information"""

    name: str
    code: Code


class Address(BaseModel):
    """Address with country reference"""

    street: str
    city: str
    zipCode: str | None = None
    country: Country = Field(..., description="Reference to Country")


class Office(BaseModel):
    """Office with address reference"""

    name: str
    address: Address = Field(..., description="Reference to Address (which references Country)")
    employees: int | None = Field(None, ge=1)


class Organization(BaseModel):
    """Organization schema with chained internal references"""

    id: UUID
    name: str
    headquarters: Office = Field(..., description="Main office (references Office → Address → Country)")
    branches: list[Office] | None = Field(None, description="Branch offices (reuses Office type multiple times)")
