// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

/**
 * Payload for pong event (minimal response)
 */
export interface PongPayload {
  /**
   * Pong response timestamp
   * @format date-time
   */
  timestamp?: string;
}

export const PongPayloadSchema = z.object({
  timestamp: z.iso.datetime().optional().meta({ description: "Pong response timestamp" }),
}).meta({ description: "Payload for pong event (minimal response)" });
