// Code generated by schemagen. DO NOT EDIT.

/**
 * Type with cyclic reference to itself
 */
export interface CyclicRef {
  /** Unique identifier */
  id: string;
  name?: string;
  /** Reference to parent node (cyclic) */
  parent?: CyclicRef;
  /** Child nodes (cyclic) */
  children?: CyclicRef[];
}
