// Code generated by schemagen. DO NOT EDIT.

/**
 * This has "double quotes" and '''triple single''' and """triple double""" quotes
 */
export interface DescriptionQuotes {
  /** Field with "quotes" and \backslash in description */
  field?: string;
}
