// Code generated by schemagen. DO NOT EDIT.

package models

import (
	"github.com/go-playground/validator/v10"
	"github.com/mirpo/schemagen/testdata/expected/settings"
)

// Config Application configuration (YAML format test)
type Config struct {
	AppName string `json:"appName" validate:"required"`
	Settings *Settings `json:"settings,omitempty"`
	Version string `json:"version" validate:"required"`
}