// Code generated by schemagen. DO NOT EDIT.

package models

import (
	"github.com/go-playground/validator/v10"
)

type LogLevel string

const (
	LogLevelDEBUG LogLevel = "debug"
	LogLevelINFO LogLevel = "info"
	LogLevelWARN LogLevel = "warn"
	LogLevelERROR LogLevel = "error"
)

// Settings Application settings
type Settings struct {
	Debug *bool `json:"debug,omitempty"`
	LogLevel *LogLevel `json:"logLevel,omitempty"`
	MaxConnections *int `json:"maxConnections,omitempty" validate:"gte=1"`
}