// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

export const TypeSchema = z.enum(["email"]);

export type Type = z.infer<typeof TypeSchema>;

/**
 * Email channel configuration
 */
export const ChannelSchema = z.object({
  subject: z.string(),
  to: z.email(),
  type: TypeSchema,
}).meta({ description: "Email channel configuration" });

export type Channel = z.infer<typeof ChannelSchema>;

export const Type2Schema = z.enum(["sms"]);

export type Type2 = z.infer<typeof Type2Schema>;

/**
 * SMS channel configuration
 */
export const Channel1Schema = z.object({
  countryCode: z.string().optional(),
  phoneNumber: z.string(),
  type: Type2Schema,
}).meta({ description: "SMS channel configuration" });

export type Channel1 = z.infer<typeof Channel1Schema>;

export const Type3Schema = z.enum(["push"]);

export type Type3 = z.infer<typeof Type3Schema>;

/**
 * Push notification configuration
 */
export const Channel2Schema = z.object({
  badge: z.number().optional(),
  deviceId: z.string(),
  type: Type3Schema,
}).meta({ description: "Push notification configuration" });

export type Channel2 = z.infer<typeof Channel2Schema>;

export const FormatSchema = z.enum(["text"]);

export type Format = z.infer<typeof FormatSchema>;

/**
 * Plain text content
 */
export const ContentSchema = z.object({
  body: z.string(),
  format: FormatSchema,
}).meta({ description: "Plain text content" });

export type Content = z.infer<typeof ContentSchema>;

export const Format2Schema = z.enum(["html"]);

export type Format2 = z.infer<typeof Format2Schema>;

/**
 * HTML content
 */
export const Content1Schema = z.object({
  body: z.string(),
  css: z.string().optional(),
  format: Format2Schema,
}).meta({ description: "HTML content" });

export type Content1 = z.infer<typeof Content1Schema>;

/**
 * Notification priority level
 */
export const PrioritySchema = z.enum(["low", "normal", "high", "urgent"]).meta({ description: "Notification priority level" });

export type Priority = z.infer<typeof PrioritySchema>;

/**
 * A notification that can be sent via multiple channels
 */
export const NotificationSchema = z.object({
  id: z.string().meta({ description: "Unique notification ID" }),
  timestamp: z.iso.datetime().meta({ description: "When the notification was created" }),
  channel: z.union([ChannelSchema, Channel1Schema, Channel2Schema]).meta({ description: "Delivery channel configuration (email, SMS, or push)" }),
  content: z.union([ContentSchema, Content1Schema]).meta({ description: "Notification content (text or HTML)" }),
  priority: PrioritySchema.optional().meta({ description: "Notification priority level" }),
}).meta({ description: "A notification that can be sent via multiple channels" });

export type Notification = z.infer<typeof NotificationSchema>;
