# Code generated by schemagen. DO NOT EDIT.

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


class Address(BaseModel):
    name: str
    street: str
    city: str
    state: str | None = None
    zipCode: str | None = None
    country: str


class Currency(str, Enum):
    USD = "USD"
    EUR = "EUR"
    GBP = "GBP"
    JPY = "JPY"


class Money(BaseModel):
    amount: float = Field(..., ge=0)
    currency: Currency


class LineItem(BaseModel):
    productId: str
    productName: str
    quantity: int = Field(..., ge=1)
    unitPrice: Money
    totalPrice: Money


class Status(str, Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    SHIPPED = "shipped"
    DELIVERED = "delivered"
    CANCELLED = "cancelled"


class EcommerceOrder(BaseModel):
    """Production-like ecommerce order schema"""

    orderId: str
    customerId: str
    orderDate: datetime
    status: Status
    items: list[LineItem] = Field(..., min_length=1)
    shippingAddress: Address
    billingAddress: Address | None = None
    subtotal: Money | None = None
    tax: Money | None = None
    shipping: Money | None = None
    total: Money
