// Code generated by schemagen. DO NOT EDIT.

package models

import (
	"github.com/go-playground/validator/v10"
)

type Container struct {
	Name string `json:"name" validate:"required"`
	Data interface{} `json:"data" validate:"required"`
}