// Code generated by schemagen. DO NOT EDIT.

package models

import (
	_ "github.com/go-playground/validator/v10"
)

type Container struct {
	Name string `json:"name" validate:"required"`
	Data any `json:"data" validate:"required"`
}