// Code generated by schemagen. DO NOT EDIT.

package models

import (
	_ "github.com/go-playground/validator/v10"
)

// Simple A simple test schema
type Simple struct {
	// The name field
	Name string `json:"name" validate:"required"`
	// The numeric value
	Value *int `json:"value,omitempty"`
}