// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

/**
 * All primitive types
 */
export interface Primitives {
  booleanVal: boolean;
  integerVal: number;
  numberVal: number;
  stringVal: string;
}

export const PrimitivesSchema = z.object({
  booleanVal: z.boolean(),
  integerVal: z.int(),
  numberVal: z.number(),
  stringVal: z.string(),
}).meta({ description: "All primitive types" });

/**
 * String formats for validation
 */
export interface Formats {
  /**
   * Date only (YYYY-MM-DD)
   * @format date
   */
  date?: string;
  /**
   * Full timestamp with timezone
   * @format date-time
   */
  dateTime?: string;
  /**
   * User email address
   * @format email
   */
  email?: string;
  /**
   * IPv4 address
   * @format ipv4
   */
  ipv4?: string;
  /**
   * IPv6 address
   * @format ipv6
   */
  ipv6?: string;
  /**
   * Time only (HH:MM:SS)
   * @format time
   */
  time?: string;
  /**
   * Resource URL
   * @format uri
   */
  uri?: string;
  /**
   * Unique identifier
   * @format uuid
   */
  uuid?: string;
}

export const FormatsSchema = z.object({
  date: z.iso.date().optional().meta({ description: "Date only (YYYY-MM-DD)" }),
  dateTime: z.iso.datetime().optional().meta({ description: "Full timestamp with timezone" }),
  email: z.email().optional().meta({ description: "User email address" }),
  ipv4: z.ipv4().optional().meta({ description: "IPv4 address" }),
  ipv6: z.ipv6().optional().meta({ description: "IPv6 address" }),
  time: z.iso.time().optional().meta({ description: "Time only (HH:MM:SS)" }),
  uri: z.url().optional().meta({ description: "Resource URL" }),
  uuid: z.uuid().optional().meta({ description: "Unique identifier" }),
}).meta({ description: "String formats for validation" });

export interface Arrays {
  /** Array with size constraints */
  minMaxArray?: string[];
}

export const ArraysSchema = z.object({
  minMaxArray: z.array(z.string()).min(1).max(10).optional().meta({ description: "Array with size constraints" }),
});

export interface Numbers {
  /** Number with exclusive bounds */
  exclusiveRange?: number;
  /** Integer with constraints */
  minMaxInteger?: number;
  /** Number with inclusive bounds */
  minMaxNumber?: number;
}

export const NumbersSchema = z.object({
  exclusiveRange: z.number().gt(0).lt(100).optional().meta({ description: "Number with exclusive bounds" }),
  minMaxInteger: z.int().gte(1).lte(999).optional().meta({ description: "Integer with constraints" }),
  minMaxNumber: z.number().gte(0).lte(100).optional().meta({ description: "Number with inclusive bounds" }),
});

export interface Strings {
  /** String with length constraints */
  minMaxString?: string;
  /** String matching regex pattern */
  patternString?: string;
}

export const StringsSchema = z.object({
  minMaxString: z.string().min(5).max(50).optional().meta({ description: "String with length constraints" }),
  patternString: z.string().regex(/^[A-Z][a-z]+$/).optional().meta({ description: "String matching regex pattern" }),
});

/**
 * Validation constraints
 */
export interface Constraints {
  arrays?: Arrays;
  numbers?: Numbers;
  strings?: Strings;
}

export const ConstraintsSchema = z.object({
  arrays: ArraysSchema.optional(),
  numbers: NumbersSchema.optional(),
  strings: StringsSchema.optional(),
}).meta({ description: "Validation constraints" });

/**
 * Mixed type enumeration
 */
export type MixedEnum = "string" | 42 | true | null;

export const MixedEnumSchema = z.union([z.literal("string"), z.literal(42), z.literal(true), z.literal(null)]).meta({ description: "Mixed type enumeration" });

/**
 * Number enumeration
 */
export enum NumberEnum {
  N_1 = 1,
  N_2 = 2,
  N_3 = 3
}

export const NumberEnumSchema = z.union([z.literal(1), z.literal(2), z.literal(3)]).meta({ description: "Number enumeration" });

/**
 * String enumeration
 */
export type StringEnum = "option1" | "option2" | "option3";

export const StringEnumSchema = z.enum(["option1", "option2", "option3"]).meta({ description: "String enumeration" });

/**
 * Enumeration types
 */
export interface Enums {
  /** Mixed type enumeration */
  mixedEnum?: MixedEnum;
  /** Number enumeration */
  numberEnum?: NumberEnum;
  /** String enumeration */
  stringEnum?: StringEnum;
}

export const EnumsSchema = z.object({
  mixedEnum: MixedEnumSchema.optional().meta({ description: "Mixed type enumeration" }),
  numberEnum: NumberEnumSchema.optional().meta({ description: "Number enumeration" }),
  stringEnum: StringEnumSchema.optional().meta({ description: "String enumeration" }),
}).meta({ description: "Enumeration types" });

export interface ObjectArrayItem {
  id?: string;
  value?: number;
}

export const ObjectArrayItemSchema = z.object({
  id: z.string().optional(),
  value: z.number().optional(),
});

/**
 * Array types
 */
export interface Arrays2 {
  /** Array of numbers */
  numberArray?: number[];
  /** Array of objects */
  objectArray?: ObjectArrayItem[];
  /** Array of strings */
  stringArray?: string[];
}

export const Arrays2Schema = z.object({
  numberArray: z.array(z.number()).optional().meta({ description: "Array of numbers" }),
  objectArray: z.array(ObjectArrayItemSchema).optional().meta({ description: "Array of objects" }),
  stringArray: z.array(z.string()).optional().meta({ description: "Array of strings" }),
}).meta({ description: "Array types" });

export interface Level2 {
  /** Three levels deep */
  level3?: string;
}

export const Level2Schema = z.object({
  level3: z.string().optional().meta({ description: "Three levels deep" }),
});

export interface Level1 {
  level2?: Level2;
}

export const Level1Schema = z.object({
  level2: Level2Schema.optional(),
});

/**
 * Nested object structure
 */
export interface Nested {
  level1?: Level1;
}

export const NestedSchema = z.object({
  level1: Level1Schema.optional(),
}).meta({ description: "Nested object structure" });

export interface OptionalObject {
  field?: string;
}

export const OptionalObjectSchema = z.object({
  field: z.string().optional(),
});

/**
 * Required vs optional fields
 */
export interface Nullable {
  optionalArray?: string[];
  optionalNumber?: number;
  optionalObject?: OptionalObject;
  /** This field is optional */
  optionalString?: string;
  /** This field is required */
  requiredString: string;
}

export const NullableSchema = z.object({
  optionalArray: z.array(z.string()).optional(),
  optionalNumber: z.number().optional(),
  optionalObject: OptionalObjectSchema.optional(),
  optionalString: z.string().optional().meta({ description: "This field is optional" }),
  requiredString: z.string().meta({ description: "This field is required" }),
}).meta({ description: "Required vs optional fields" });

/**
 * Any additional properties allowed
 */
export interface Flexible {
  enabled?: boolean;
  version: string;
}

export const FlexibleSchema = z.looseObject({
  enabled: z.boolean().optional(),
  version: z.string(),
}).meta({ description: "Any additional properties allowed" });

/**
 * No additional properties allowed
 */
export interface Strict {
  id: string;
  name?: string;
}

export const StrictSchema = z.strictObject({
  id: z.string(),
  name: z.string().optional(),
}).meta({ description: "No additional properties allowed" });

/**
 * Additional properties must be numbers
 */
export interface TypedMap {
  source?: string;
  timestamp: string;
}

export const TypedMapSchema = z.object({
  source: z.string().optional(),
  timestamp: z.string(),
}).catchall(z.number()).meta({ description: "Additional properties must be numbers" });

/**
 * Additional properties patterns
 */
export interface AdditionalProps {
  /** Any additional properties allowed */
  flexible?: Flexible;
  /** No additional properties allowed */
  strict?: Strict;
  /** Additional properties must be numbers */
  typedMap?: TypedMap;
}

export const AdditionalPropsSchema = z.object({
  flexible: FlexibleSchema.optional().meta({ description: "Any additional properties allowed" }),
  strict: StrictSchema.optional().meta({ description: "No additional properties allowed" }),
  typedMap: TypedMapSchema.optional().meta({ description: "Additional properties must be numbers" }),
}).meta({ description: "Additional properties patterns" });

/**
 * Reserved keywords in TypeScript and Python
 */
export interface ReservedKeywords {
  as?: string;
  async?: string;
  "await"?: string;
  "class"?: string;
  def?: string;
  "export"?: string;
  from?: string;
  "import"?: string;
  "interface"?: string;
  lambda?: string;
  "return"?: string;
  type?: string;
  "yield"?: string;
}

export const ReservedKeywordsSchema = z.object({
  as: z.string().optional(),
  async: z.string().optional(),
  "await": z.string().optional(),
  "class": z.string().optional(),
  def: z.string().optional(),
  "export": z.string().optional(),
  from: z.string().optional(),
  "import": z.string().optional(),
  "interface": z.string().optional(),
  lambda: z.string().optional(),
  "return": z.string().optional(),
  type: z.string().optional(),
  "yield": z.string().optional(),
}).meta({ description: "Reserved keywords in TypeScript and Python" });

/**
 * Special characters in property names
 */
export interface SpecialChars {
  $dollar?: string;
  "123numeric"?: string;
  "@special"?: string;
  PascalCase?: string;
  camelCase?: string;
  "kebab-case"?: string;
  snake_case?: string;
  "with spaces"?: string;
  "with.dots"?: string;
}

export const SpecialCharsSchema = z.object({
  $dollar: z.string().optional(),
  "123numeric": z.string().optional(),
  "@special": z.string().optional(),
  PascalCase: z.string().optional(),
  camelCase: z.string().optional(),
  "kebab-case": z.string().optional(),
  snake_case: z.string().optional(),
  "with spaces": z.string().optional(),
  "with.dots": z.string().optional(),
}).meta({ description: "Special characters in property names" });

/**
 * Edge cases: reserved keywords and special characters
 */
export interface EdgeCases {
  /** Empty object with no properties */
  emptyConfig?: Record<string, any>;
  /** Reserved keywords in TypeScript and Python */
  reservedKeywords?: ReservedKeywords;
  /** Special characters in property names */
  specialChars?: SpecialChars;
}

export const EdgeCasesSchema = z.object({
  emptyConfig: z.record(z.string(), z.unknown()).optional().meta({ description: "Empty object with no properties" }),
  reservedKeywords: ReservedKeywordsSchema.optional().meta({ description: "Reserved keywords in TypeScript and Python" }),
  specialChars: SpecialCharsSchema.optional().meta({ description: "Special characters in property names" }),
}).meta({ description: "Edge cases: reserved keywords and special characters" });

/**
 * Comprehensive test of all basic types, formats, constraints, and edge cases
 */
export interface Foundation {
  /** All primitive types */
  primitives: Primitives;
  /** String formats for validation */
  formats?: Formats;
  /** Validation constraints */
  constraints?: Constraints;
  /** Enumeration types */
  enums?: Enums;
  /** Array types */
  arrays?: Arrays2;
  /** Nested object structure */
  nested?: Nested;
  /** Required vs optional fields */
  nullable?: Nullable;
  /** Additional properties patterns */
  additionalProps?: AdditionalProps;
  /** Edge cases: reserved keywords and special characters */
  edgeCases?: EdgeCases;
}

export const FoundationSchema = z.object({
  primitives: PrimitivesSchema.meta({ description: "All primitive types" }),
  formats: FormatsSchema.optional().meta({ description: "String formats for validation" }),
  constraints: ConstraintsSchema.optional().meta({ description: "Validation constraints" }),
  enums: EnumsSchema.optional().meta({ description: "Enumeration types" }),
  arrays: Arrays2Schema.optional().meta({ description: "Array types" }),
  nested: NestedSchema.optional().meta({ description: "Nested object structure" }),
  nullable: NullableSchema.optional().meta({ description: "Required vs optional fields" }),
  additionalProps: AdditionalPropsSchema.optional().meta({ description: "Additional properties patterns" }),
  edgeCases: EdgeCasesSchema.optional().meta({ description: "Edge cases: reserved keywords and special characters" }),
}).meta({ description: "Comprehensive test of all basic types, formats, constraints, and edge cases" });
