// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

export type Currency = "USD" | "EUR" | "GBP" | "JPY";

export const CurrencySchema = z.enum(["USD", "EUR", "GBP", "JPY"]);

export interface Money {
  amount: number;
  currency: Currency;
}

export const MoneySchema = z.object({
  amount: z.number().gte(0),
  currency: CurrencySchema,
});

export interface Address {
  name: string;
  street: string;
  city: string;
  state?: string;
  zipCode?: string;
  country: string;
}

export const AddressSchema = z.object({
  name: z.string(),
  street: z.string(),
  city: z.string(),
  state: z.string().optional(),
  zipCode: z.string().optional(),
  country: z.string(),
});

export interface LineItem {
  productId: string;
  productName: string;
  quantity: number;
  unitPrice: Money;
  totalPrice: Money;
}

export const LineItemSchema = z.object({
  productId: z.string(),
  productName: z.string(),
  quantity: z.int().gte(1),
  unitPrice: MoneySchema,
  totalPrice: MoneySchema,
});

export type Status = "pending" | "processing" | "shipped" | "delivered" | "cancelled";

export const StatusSchema = z.enum(["pending", "processing", "shipped", "delivered", "cancelled"]);

/**
 * Production-like ecommerce order schema
 */
export interface EcommerceOrder {
  orderId: string;
  customerId: string;
  /**
   * @format date-time
   */
  orderDate: string;
  status: Status;
  items: LineItem[];
  shippingAddress: Address;
  billingAddress?: Address;
  subtotal?: Money;
  tax?: Money;
  shipping?: Money;
  total: Money;
}

export const EcommerceOrderSchema = z.object({
  orderId: z.string(),
  customerId: z.string(),
  orderDate: z.iso.datetime(),
  status: StatusSchema,
  items: z.array(LineItemSchema).min(1),
  shippingAddress: AddressSchema,
  billingAddress: AddressSchema.optional(),
  subtotal: MoneySchema.optional(),
  tax: MoneySchema.optional(),
  shipping: MoneySchema.optional(),
  total: MoneySchema,
}).meta({ description: "Production-like ecommerce order schema" });
