# Code generated by schemagen. DO NOT EDIT.

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field, EmailStr


class Format(str, Enum):
    TEXT = "text"


class Content(BaseModel):
    """Plain text content"""

    body: str
    format: Format


class Format2(str, Enum):
    HTML = "html"


class Content1(BaseModel):
    """HTML content"""

    body: str
    css: str | None = None
    format: Format2


class Priority(str, Enum):
    """Notification priority level"""

    LOW = "low"
    NORMAL = "normal"
    HIGH = "high"
    URGENT = "urgent"


class Type(str, Enum):
    EMAIL = "email"


class Channel(BaseModel):
    """Email channel configuration"""

    subject: str
    to: EmailStr
    type: Type


class Type2(str, Enum):
    SMS = "sms"


class Channel1(BaseModel):
    """SMS channel configuration"""

    countryCode: str | None = None
    phoneNumber: str
    type: Type2


class Type3(str, Enum):
    PUSH = "push"


class Channel2(BaseModel):
    """Push notification configuration"""

    badge: float | None = None
    deviceId: str
    type: Type3


class Notification(BaseModel):
    """A notification that can be sent via multiple channels"""

    id: str = Field(..., description="Unique notification ID")
    timestamp: datetime = Field(..., description="When the notification was created")
    channel: Channel | Channel1 | Channel2 = Field(..., description="Delivery channel configuration (email, SMS, or push)")
    content: Content | Content1 = Field(..., description="Notification content (text or HTML)")
    priority: Priority | None = Field(None, description="Notification priority level")
