// Code generated by schemagen. DO NOT EDIT.

export interface IdObject {
  /**
   * @format uuid
   */
  id: string;
}

export interface Timestamped {
  /**
   * @format date-time
   */
  createdAt: string;
  /**
   * @format date-time
   */
  updatedAt?: string;
}

export interface Person {
  /**
   * @format email
   */
  email?: string;
  name?: string;
}

export interface Node {
  value?: string;
  next?: Node;
}

export interface Payload {
  data: string;
  type: "A";
}

export interface Payload1 {
  data: number;
  type: "B";
}

/**
 * One schema to test everything
 */
export type MegaTest = IdObject & Timestamped & {
  tags: string[];
  owner?: Person;
  status: "active" | "paused";
  meta?: Record<string, string>;
  payload?: Payload | Payload1;
  node?: Node;
};
