// Code generated by schemagen. DO NOT EDIT.

/**
 * Payload for ping event
 */
export interface PingPayload {
  /**
   * Ping timestamp
   * @format date-time
   */
  timestamp: string;
  /** Time to live in milliseconds */
  ttl: number;
  /** Ping sequence number */
  sequence?: number;
}
