// Code generated by schemagen. DO NOT EDIT.

/**
 * Payload for subscribe event
 */
export interface SubscribePayload {
  /** Topic to subscribe to */
  topic: string;
  /** Subscription filters */
  filters?: Record<string, string>;
  /** Quality of service level */
  qos?: number;
}
