// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

/**
 * Payload for ping event
 */
export const PingPayloadSchema = z.object({
  timestamp: z.iso.datetime().meta({ description: "Ping timestamp" }),
  ttl: z.int().gte(0).meta({ description: "Time to live in milliseconds" }),
  sequence: z.int().gte(0).optional().meta({ description: "Ping sequence number" }),
}).meta({ description: "Payload for ping event" });

export type PingPayload = z.infer<typeof PingPayloadSchema>;
