// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

/**
 * Payload for subscribe event
 */
export const SubscribePayloadSchema = z.object({
  topic: z.string().meta({ description: "Topic to subscribe to" }),
  filters: z.record(z.string(), z.string()).optional().meta({ description: "Subscription filters" }),
  qos: z.int().gte(0).lte(2).optional().meta({ description: "Quality of service level" }),
}).meta({ description: "Payload for subscribe event" });

export type SubscribePayload = z.infer<typeof SubscribePayloadSchema>;
