// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

/**
 * Payload for unsubscribe event
 */
export const UnsubscribePayloadSchema = z.object({
  subscriptionId: z.uuid().meta({ description: "ID of subscription to cancel" }),
  reason: z.string().optional().meta({ description: "Reason for unsubscribing" }),
}).meta({ description: "Payload for unsubscribe event" });

export type UnsubscribePayload = z.infer<typeof UnsubscribePayloadSchema>;
