// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

/**
 * This has "double quotes" and '''triple single''' and """triple double""" quotes
 */
export const DescriptionQuotesSchema = z.object({
  field: z.string().optional().meta({ description: "Field with \"quotes\" and \\backslash in description" }),
}).meta({ description: "This has \"double quotes\" and '''triple single''' and \"\"\"triple double\"\"\" quotes" });

export type DescriptionQuotes = z.infer<typeof DescriptionQuotesSchema>;
