// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

/**
 * Enum with complex values (objects/arrays) - all preserved in output
 */
export const EnumComplexSchema = z.union([z.literal("simple"), z.object({ complex: z.literal(true) }).strict(), z.literal(42), z.tuple([z.literal("array"), z.literal("value")])]).meta({ description: "Enum with complex values (objects/arrays) - all preserved in output" });

export type EnumComplex = z.infer<typeof EnumComplexSchema>;
