// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

/**
 * Object with special property names requiring aliases
 */
export const SpecialPropsSchema = z.object({
  "kebab-case": z.string().meta({ description: "Property with kebab-case name" }),
  "with spaces": z.string().optional().meta({ description: "Property with spaces" }),
  "123numeric": z.int().optional().meta({ description: "Property starting with number" }),
  $dollar: z.boolean().optional().meta({ description: "Property starting with dollar" }),
  "class": z.string().optional().meta({ description: "Python reserved keyword" }),
  from: z.string().optional().meta({ description: "Python reserved keyword" }),
}).meta({ description: "Object with special property names requiring aliases" });

export type SpecialProps = z.infer<typeof SpecialPropsSchema>;
