// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

/**
 * Union with nullable members
 */
export const UnionNullableSchema = z.union([z.string(), z.unknown().nullable(), z.int()]).meta({ description: "Union with nullable members" });

export type UnionNullable = z.infer<typeof UnionNullableSchema>;
