// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

export interface Container {
  name: string;
  data: any;
}

export const ContainerSchema = z.object({
  name: z.string(),
  data: z.unknown(),
});
