// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

/**
 * A simple test schema
 */
export interface Simple {
  /** The name field */
  name: string;
  /** The numeric value */
  value?: number;
}

export const SimpleSchema = z.object({
  name: z.string().meta({ description: "The name field" }),
  value: z.int().optional().meta({ description: "The numeric value" }),
}).meta({ description: "A simple test schema" });
