// Code generated by schemagen. DO NOT EDIT.

export type Currency = "USD" | "EUR" | "GBP" | "JPY";

export interface Money {
  amount: number;
  currency: Currency;
}

export interface Address {
  name: string;
  street: string;
  city: string;
  state?: string;
  zipCode?: string;
  country: string;
}

export interface LineItem {
  productId: string;
  productName: string;
  quantity: number;
  unitPrice: Money;
  totalPrice: Money;
}

export type Status = "pending" | "processing" | "shipped" | "delivered" | "cancelled";

/**
 * Production-like ecommerce order schema
 */
export interface EcommerceOrder {
  orderId: string;
  customerId: string;
  /**
   * @format date-time
   */
  orderDate: string;
  status: Status;
  items: LineItem[];
  shippingAddress: Address;
  billingAddress?: Address;
  subtotal?: Money;
  tax?: Money;
  shipping?: Money;
  total: Money;
}
