// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

export const ContainerSchema = z.object({
  name: z.string(),
  data: z.unknown(),
});

export type Container = z.infer<typeof ContainerSchema>;
