// Code generated by schemagen. DO NOT EDIT.

import { z } from 'zod';

/**
 * A simple test schema
 */
export const SimpleSchema = z.object({
  name: z.string().meta({ description: "The name field" }),
  value: z.int().optional().meta({ description: "The numeric value" }),
}).meta({ description: "A simple test schema" });

export type Simple = z.infer<typeof SimpleSchema>;
