// Code generated by schemagen. DO NOT EDIT.

/**
 * Payload for pong event (minimal response)
 */
export interface PongPayload {
  /**
   * Pong response timestamp
   * @format date-time
   */
  timestamp?: string;
}
