// Code generated by schemagen. DO NOT EDIT.

/**
 * Payload for unsubscribe event
 */
export interface UnsubscribePayload {
  /**
   * ID of subscription to cancel
   * @format uuid
   */
  subscriptionId: string;
  /** Reason for unsubscribing */
  reason?: string;
}
