// Code generated by schemagen. DO NOT EDIT.

/**
 * Object with special property names requiring aliases
 */
export interface SpecialProps {
  /** Property with kebab-case name */
  "kebab-case": string;
  /** Property with spaces */
  "with spaces"?: string;
  /** Property starting with number */
  "123numeric"?: number;
  /** Property starting with dollar */
  $dollar?: boolean;
  /** Python reserved keyword */
  "class"?: string;
  /** Python reserved keyword */
  from?: string;
}
